### ISSUE TITLE
Can add new config for specify GET param & secret value to clear cache

### ISSUE THREAD

**Issue by khanhvu14** [spatie/laravel-responsecache#100]
I have a problem.
I want to clear cache directly via custom GET param
Ex: bds123.vn?clear='all' || Ex: bds123.vn?clear='1'
This means that the RequestHasher will not include this GET param when generate hash key?
Do you have add it to current config?

**Comment by tbrennanNHB** [comment]
If you look in "RequestHasher.php" you see the function "getHashFor" with as response:
`return 'laravel-responsecache-'.md5(
            "{$request->getUri()}/{$request->getMethod()}/".$this->cacheProfile->cacheNameSuffix($request)
        );`

If you print the "$request->getUri()" result you will see for example: "bds123.vn/?clear=%27all%27".

So, the above result (the request URI) is added to the md5, which means that your GET parameters are added in the generated hash key.

**Comment by khanhvu14** [comment]
Yes right, so I need config to ingore this GET paramater, so hashrequester is not added this GET parameter

**Comment by sebastiandedeyne** [comment]
Modifying the request hasher's behaviour isn't supported in the current version and won't be added either. We'll provide more freedom for request hashing in the next major version of this package. 

See #112
