### ISSUE TITLE
Can not build response if cache was deleted while reading cache data

### ISSUE THREAD

**Issue by ndlinh** [spatie/laravel-responsecache#102]
I use Redis for caching. There is a case response can not unserialized if I clear cache. I got exception like this:

`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Spatie\ResponseCache\ResponseSerializer::buildResponse() must be of the type array, boolean given, called in /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/ResponseSerializer.php on line 22 in /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/ResponseSerializer.php:47 Stack trace: #0 /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/ResponseSerializer.php(22): Spatie\ResponseCache\ResponseSerializer->buildResponse(false) #1 /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/ResponseCacheRepository.php(39): Spatie\ResponseCache\ResponseSerializer->unserialize(NULL) #2 /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/ResponseCache.php(69): Spatie\ResponseCache\ResponseCacheRepository->get('responsecache-8...') #3 /var/www/html/prod/releases/20171010100757/vendor/spatie/laravel-responsecache/src/Middlewares/CacheResponse.php(28): Spatie\ResponseCache\ResponseCache->getCachedResponseFor(Object(Illuminate\Http\Request)) #4 /var/www/html/prod/releases/20171010100757/vendor/illuminate/pipeline/Pipeline.php(148): Spatie\ResponseCache\Middlewares\CacheResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #6 /var/www/html/prod/releases/20171010100757/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #7 /var/www/html/prod/releases/20171010100757/vendor/illuminate/session/Middleware/StartSession.php(64): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request)) #8 /var/www/html/prod/releases/20171010100757/vendor/illuminate/pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #10 /var/www/html/prod/releases/20171010100757/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #11 /var/www/html/prod/releases/20171010100757/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request)) #12 /var/www/html/prod/releases/20171010100757/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #13 /var/www/html/prod/releases/20171010100757/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure)) #14 /var/www/html/prod/releases/20171010100757/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL) #15 /var/www/html/prod/releases/20171010100757/public/index.php(34): Laravel\Lumen\Application->run() #16 {main}`

**Comment by sebastiandedeyne** [comment]
We can't fix this now, but we added better exception handling, see #111.

Released in `4.1.1`
