### ISSUE TITLE
bypass cache when user is logged in 

### ISSUE THREAD

**Issue by monovm** [spatie/laravel-responsecache#103]
i wan to know can we bypass cache after user logged in or when session id is exist ? 
regards

**Comment by sebastiandedeyne** [comment]
You can write your own cache profile, and implement your own `enabled` method.

https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile

**Comment by monovm** [comment]
Dear sebastiandedeyne
we use laravel 5.4 
we need bypass cache after user logged in also we do not use laravel auth engine 
we have our own 

regards

**Comment by sebastiandedeyne** [comment]
You can place whatever logic you want in your custom `enable` method. For example, you could inherit this package's `CacheAllSuccessfulGetRequests` profile and override the `enabled` method.

```php
use Illuminate\Http\Request;
use Spatie\ResponseCache\ CacheProfiles\CacheAllSuccessfulGetRequests;

class MyCacheProfile extends CacheAllSuccessfulGetRequests
{
    public function enabled(Request $request): bool
    {
        if (! parent::enabled($request)) {
            return false;
        }

        return MyAuthSystem::isAuthenticated(); // Or whatever else you need to do
    }
}
```
