### ISSUE TITLE
doNotCacheResponse middleware does not work. Laravel 5.5

### ISSUE THREAD

**Issue by goszowski** [spatie/laravel-responsecache#108]
<img width="394" alt="screenshot at dec 02 16-02-38" src="https://user-images.githubusercontent.com/10208931/33516359-3fe5b652-d77a-11e7-8e01-95d9358bcccb.png">

<img width="711" alt="screenshot at dec 02 16-01-38" src="https://user-images.githubusercontent.com/10208931/33516345-1ffb1b84-d77a-11e7-9272-3c13bbc30f6f.png">

But my CSRF token does not change and makes a mistake

**Comment by goszowski** [comment]
The page has expired due to inactivity. Please refresh and try again.

**Comment by freekmurze** [comment]
Please review this section in the readme: https://github.com/spatie/laravel-responsecache#csrf-tokens

**Comment by goszowski** [comment]
It is disabled. This can be seen on the first screenshot.

**Comment by goszowski** [comment]
It is disabled for all auth routes, but does not work. Returned response is cached.

**Comment by thequiet** [comment]
@goszowski The screenshot to which your referring does not show CSRF being disabled, it just shows that this package is disabled. If it was previously enabled before this, you will need to clear the entire cache and start over.

**Comment by goszowski** [comment]
Forced cache cleaning solved this problem. Thank you.
