### ISSUE TITLE
Dynamic View Serving

### ISSUE THREAD

**Issue by flames0fhell** [spatie/laravel-responsecache#109]
How to caching separate view by User-Agent, separating cache between mobile and desktop view by User Agent.

**Comment by sebastiandedeyne** [comment]
You'll need to write your own `CacheProfile`, and use the `cacheNameSuffix` method to create an identifier for the request based on the url and user-agent. That way you can cache a different version of the page per user agent.

https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile
