### ISSUE TITLE
Make RequestHasher fully pluggable

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-responsecache#112]
So we can provide more options than just the suffix

**Comment by khanhvu14** [comment]
When I have a Url with pagination or some GET parameter, How can flush all urls.
Can provide option to forget or clear cache with multi url? Ex: REGEX.

Example my case:
- https://bds123.vn/cho-thue-can-ho-chung-cu.html 
- https://bds123.vn/cho-thue-can-ho-chung-cu.html?page=1
- https://bds123.vn/cho-thue-can-ho-chung-cu.html?page=2
...
- https://bds123.vn/cho-thue-can-ho-chung-cu.html?price=asc

**Comment by sebastiandedeyne** [comment]
See #90 

Please open a new issue if you have another question that's not relevant to the original issue.

**Comment by freekmurze** [comment]
Implemented and we be available in `v6` of the package.
