### ISSUE TITLE
Installing on L5.4

### ISSUE THREAD

**Issue by meysamjavadi** [spatie/laravel-responsecache#117]
What should i do for this problem? 
I use L5.4

> 
> Problem 1
>     - Installation request for spatie/laravel-responsecache dev-master -> satisfiable by spatie/laravel-responsecache[dev-master].
>     - Conclusion: remove laravel/framework v5.4.0
>     - Conclusion: don't install laravel/framework v5.4.0
>     - spatie/laravel-responsecache dev-master requires illuminate/cache ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.6.x-dev], illuminate/cache[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.6.0, v5.6.1, v5.6.2, v5.6.3].
>     - Can only install one of: laravel/framework[5.6.x-dev, v5.4.0].
>     - don't install illuminate/cache 5.5.x-dev|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.0|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.16|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.17|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.2|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.28|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.33|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.5.34|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache 5.6.x-dev|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.6.0|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.6.1|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.6.2|don't install laravel/framework v5.4.0
>     - don't install illuminate/cache v5.6.3|don't install laravel/framework v5.4.0
>     - Installation request for laravel/framework 5.4.0 -> satisfiable by laravel/framework[v5.4.0].

**Comment by sebastiandedeyne** [comment]
See #116 for my response.

If it's not related, please share the contents of your composer.json, and what you'r exactly doing to get this error.
