### ISSUE TITLE
cache not being cleared up by using artisan

### ISSUE THREAD

**Issue by nekromoff** [spatie/laravel-responsecache#119]
`php artisan responsecache:clear` is used, but cache is not cleared.
`file` cache is being used / configured.

**Comment by freekmurze** [comment]
The tests indicate that this is working as intended.

If you discover why this fails for you, and that the failure is caused by the package, open up a new issue or PR.

**Comment by nekromoff** [comment]
it was caused by permissions. sudo needed to be used to clear the cache
