### ISSUE TITLE
Is there a way to support CSP nonces?

### ISSUE THREAD

**Issue by christophrumpel** [spatie/laravel-responsecache#122]
I am using this package as well as the spatie/laravel-csp one. The latter one adds dynamic nonces to responses. I guess this is similar to the CSRF tokens "problem" with this package. But when you use scripts like Google Analytics on every page, it is not an option to disable this package on all pages. Do you think there might be a way to only change the nonce in the cached response?

**Comment by freekmurze** [comment]
You could try adapting the middleware provided by this package so that, after the cached responses it retrieved it replaces the content of all nonces attributes by the one generated by the csp packages (you can get that one with a call to `cspNonce()` I believe.

**Comment by christophrumpel** [comment]
Thx, I will try that 👍

**Comment by christophrumpel** [comment]
Yep, that worked 🤘Should it be possible that I write myself another middleware that runs after the reponse-cache one so that I could switch the nonces there? This way I could handle it in my code.

**Comment by freekmurze** [comment]
I guess it would be possible, the tricky part would be to get the middlewares running in the correct order. If you manage to do that, please post your solution here, so other can benefit from that as well.

**Comment by christophrumpel** [comment]
Ok thx, I finally made it work with a custom middleware and the right order. You need to make sure this new one is running after the response cache one. Here is the middleware code:

```php
public function handle($request, Closure $next)
    {
        /** @var Response $response */
        $response = $next($request);

        $csp = $response->headers->get('Content-Security-Policy');
        $newCsp = preg_replace('/nonce-.+?(?=\')/', 'nonce-'.cspNonce(), $csp);
        $response->headers->set('Content-Security-Policy', $newCsp);

        $newContent = preg_replace('/(?<=nonce=")(.*)(?=")/', cspNonce(), $response->getContent());
        $response->setContent($newContent);

        return $response;
    }
```

I also wrote a little article about the problem and solution: https://christoph-rumpel.com/2018/03/laravel-response-caching-and-csp

**Comment by freekmurze** [comment]
Cool 👍
Thanks for sharing your solution

**Comment by christophrumpel** [comment]
Np! Would it be interesting for you to add a solution to the package itself?

**Comment by christophrumpel** [comment]
I also found a way to make it work without the nonces: https://christoph-rumpel.com/2018/03/content-security-policy-hash-algorithm-and-turbolinks

**Comment by freekmurze** [comment]
> Np! Would it be interesting for you to add a solution to the package itself?

It this can be well tested, I'd accept a PR that adds this the package. I'm thinking the PR should go to the csp package.

**Comment by damms005** [comment]
> But when you use scripts like Google Analytics on every page, it is not an option to disable this package on all pages

@christophrumpel Please can you throw more light on the issue with this package and Google Analytics? I noticed that this package somehow renders packages with Google's analytics tag section removed
