### ISSUE TITLE
Responsecache clear tagging problem

### ISSUE THREAD

**Issue by kaveczkib** [spatie/laravel-responsecache#123]
In reference to the issue #85 i discovered that in the new clear() method you use in ResponseCacherepository $this->cache->clear() instead of $this->cache->flush() and this solution causing problems when you use driver which support tagging. 
Example: using redis cache driver, the clear() method flushed the whole cache (not caring with tagging)

**Comment by cyberkiko** [comment]
Having the same issue

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this.

**Comment by freekmurze** [comment]
This is fixed in the latest version.

**Comment by adarmanto** [comment]
Using file cache driver also still delete whole cache (new version 4.4.2), meanwhile I use cache for other reason.

**Comment by z-h-z-h** [comment]
@freekmurze ResponseCache:clear() not cache_tag and deletes entire cache
