### ISSUE TITLE
Breaks Login, Logout, Register

### ISSUE THREAD

**Issue by 28development** [spatie/laravel-responsecache#125]
The package breaks the login, logout and register function of the page I always get this message after installing the package:

The page has expired due to inactivity. Please refresh and try again.

As mentioned in the docs I added this middleware `$this->middleware('doNotCacheResponse');`

In my logincontroller and registercontroller

How can I solve this in a nice way?

**Comment by sebastiandedeyne** [comment]
Are your csrf tokens cached in your logout form? That might be the problem

**Comment by AlphaGeek509** [comment]
I too am wrestiling with this issue. Any ideas?

**Comment by sebastiandedeyne** [comment]
Please provide a minimal reproduction of the issue or a failing test so we can debug this.

**Comment by sebastiandedeyne** [comment]
Feel free to reopen this issue or create a new one with a minimal reproduction.

**Comment by Peterragheb** [comment]
I'm facing this issue on 
laravel: 8.14.0
nova: 3.15.0
knowing that I'm using this library on api middleware group
```
'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Spatie\ResponseCache\Middlewares\CacheResponse::class,

        ],
```
 the nova login returns 419 page expired. When I ran `php artisan responsecache:clear` i was abele to login on nova
