### ISSUE TITLE
Error on login/redirect

### ISSUE THREAD

**Issue by EuropeanRespiratorySociety** [spatie/laravel-responsecache#13]
Hello,

When I use response cache on the whole website I have an CSRF Token (line 67) issue. 

When I do not cache the login/logout route either using the middleware on the controller or in the route
        `$this->middleware('doNotCacheResponse');`
or

	Route::get('logout', ['middleware' => 'doNotCacheResponse', 'uses' => 'Auth\AuthController@logout']);
	Route::get('login', ['middleware' => 'doNotCacheResponse', 'uses' => 'Auth\AuthController@showLoginForm']);
	Route::post('login', ['middleware' => 'doNotCacheResponse', 'uses' => 'Auth\AuthController@login']);

The login process does not work as my protected routes are not available and I am redirected to the homepage.

I am using Laravel 5.2

Any Idea?

Sam

**Comment by freekmurze** [comment]
The code you post seems ok.

Do your routes work when the package is not installed?

Can you try to clear the cache with `php artisan responsecache:clear`? Maybe you are result that were cached before you specified the `doNotCacheResponse`-middleware.

**Comment by EuropeanRespiratorySociety** [comment]
Yes they work.

I did use the artisan command, this temporarily solves the problem when I do not use the middleware, but then the token gets cached as well and I cannot login/log out anymore as I get the `TokenMismatchException in VerifyCsrfToken.php line 67:` 

This is why i tried to use the middleware, but then, I cannot login anymore. I am always redirected to the default "/"

**Comment by EuropeanRespiratorySociety** [comment]
By the way, I am on Laravel 5.2

Here is the code that gives me issues: https://github.com/EuropeanRespiratorySociety/ERSTemplate-dev

you can test the route blog. If you want to test the login, i need to give you a user/pw (I authentify through a webservice on an other db)

**Comment by freekmurze** [comment]
Hi, unfortunately I don't have the time to look into this issue so deeply. If possible write some failing tests to this package. If you want to propose a solutions, I'll be happy to look at a PR.

**Comment by mgsmus** [comment]
I also confirm this situation. If I disable cache in config, authentication backs to normal. There should be something about $request->attributes

**Comment by ecr007** [comment]
Solution: Post route applicate 'middleware' => 'doNotCacheResponse'

**Comment by mgsmus** [comment]
@ecr007 Can you explain more? We're already using middleware.

**Comment by babudesai** [comment]
i think he is saying only apply middleware to POST route and not GET.  im about to try that see if it works.

**Comment by freekmurze** [comment]
Reopen if this is still causing problems.

**Comment by LasseRafn** [comment]
@babudesai did this work for you? I also have this problem. Disabling response cache entirely fixes this though.

I've added another route file (dashboard.php) and added it in RouteServiceProvider, with the doNotCacheResponse middleware, still causes problems.

**Comment by babudesai** [comment]
Hi, I don't remember what I ended up doing after all.  I think for that project I didn't use this package

**Comment by babudesai** [comment]
But Im working on new project with laravel 5.4 I'll try it out

**Comment by LasseRafn** [comment]
The reason seems to be that it caches the unauthorized response even though the auth routes has the doNotCacheResponse middleware. I'm working on a fix 👍

**Comment by paperscissors** [comment]
This is actually still happening on the latest 1.* tree. Really wild because I've got all auth routes inside of a doNotCacheResponse middleware group. Had to drop the package implementation. I assume the 2.* tree is working a-ok though?

**Comment by LasseRafn** [comment]
I doubt it; the problem is (very likely) because it caches redirects — and I dont think that has changed, to a way that does not cache the auth redirect.👎🏻 I tried digging around in the package code for hours but couldn't find a solution

**Comment by LasseRafn** [comment]
Maybe if one added the doNotCacheResponse BEFORE the auth middleware? Haven't tested this

**Comment by lchachurski** [comment]
I have experienced similar issue, after debugging my conclusion is - 302 redirect response shouldn't be cached. In a nutshell it means "Moved Temporarily", therefore with next request, server may come up with different response like 200.

For a quick test, you can replace `CacheAllSuccessfulGetRequests` code with the following:

```php
<?php

namespace Spatie\ResponseCache\CacheProfiles;

use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CacheAllSuccessfulGetRequests extends BaseCacheProfile
{
    public function shouldCacheRequest(Request $request): bool
    {
        if ($request->ajax()) {
            return false;
        }

        if ($this->isRunningInConsole()) {
            return false;
        }

        return $request->isMethod('get');
    }

    public function shouldCacheResponse(Response $response): bool
    {
        return $response->isSuccessful(); // || $response->isRedirection();
    }
}
```

As a fix my suggestion is to exclude 302 redirections from `shouldCacheResponse` or make it at least configurable.

**Comment by lchachurski** [comment]
@freekmurze would you accept such fix for this issue? If so, I will be happy to contribute a PR.

**Comment by lchachurski** [comment]
One last thing to note, there is a working workaround. After a successful login attempt, you need to redirect to **NOT cached** route.
