### ISSUE TITLE
[Need Help] Is this package take care of updating data ?

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-responsecache#130]
Hi,
Thank you so much for this great package !
I wonder if this package updates cached data without clear command ?
For example I set cacheResponse middleware for posts list url, and I updated some posts, how can I update cached list ?

Thanks.

**Comment by AEK-BKF** [comment]
Thanks for answer !
If there a way to make one observer which listen CRUD on all models ? ^^'

**Comment by sebastiandedeyne** [comment]
This package doesn't do any automatic clearing, I recommend you do what @khanhvu14 says and listen to the necessary events in your application.
