### ISSUE TITLE
Storing different response caches for different users

### ISSUE THREAD

**Issue by ipsalej** [spatie/laravel-responsecache#131]
Hello,

I would like to store separate caches for different authenticated users, since I'm showing very different information in the same response depending on the role of the authenticated user.

Is this possible with this package? If it is, which is the recommended approach?

Thank you in advance and have a good day!

**Comment by khanhvu14** [comment]
You can override Cache Profile same with my example
```
use Illuminate\Support\Facades\Auth;
public function cacheNameSuffix(Request $request): string
    {
       $user = Auth::user();
        if($user){
            return $user->id;
        }
        return '';
    }
```

**Comment by ipsalej** [comment]
Thanks for your response!

So, taking a look into the source code of the package, at file src/CacheProfiles/BaseCacheProfile, the cacheNameSuffix does the exact same thing you're suggesting.

I imagine this does mean that the package already provides this functionality by default, doesn't it?

Cheers

**Comment by sebastiandedeyne** [comment]
The package will indeed take care of that out of the box :)

**Comment by d3vr** [comment]
Sorry for bumping an old issue, but this is a great built-in functionality and it would be perfect if it was mentioned somewhere in the `README.md`, because it wasn't clear for me until I dug into the issues. Thank you!
