### ISSUE TITLE
Refresh csrf tokens in middleware

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-responsecache#132]

**Comment by freekmurze** [comment]
We should also make it possible for the user of the package to alter the output returned from the cache.

**Comment by khanhvu14** [comment]
Still waiting next release 👍

**Comment by z-h-z-h** [comment]
Wheeen?

**Comment by freekmurze** [comment]
When somebody (maybe you?) 😄) finds the time to send us a fully tested and documented PR

**Comment by freekmurze** [comment]
We'll handle this further in #151
