### ISSUE TITLE
[Proposal] Add WarmCommand

### ISSUE THREAD

**Issue by nunomaduro** [spatie/laravel-responsecache#133]
Hey 👋

**Proposal**: Addition of a WarmCommand that calls all controllers actions with the middleware **ResponseCache**.

I can work on a pull request later if you think this proposal is a good one.

**Comment by sebastiandedeyne** [comment]
@freekmurze Should we turn this into it's own package? A crawler that essentially doesn't do anything? Could use this for Sheets too.

**Comment by freekmurze** [comment]
I'm thinking it would be to small for it's own package. Let's just require the crawler as an optional package here for that `warm` command.

@nunomaduro Go ahead and have fun creating the PR.
