### ISSUE TITLE
Service provider configuration is not overridable 

### ISSUE THREAD

**Issue by andrewmclagan** [spatie/laravel-responsecache#134]
In another package you publish (Fractal) its possible to include the package from another package and over-ride/merge its configuration in a service provider, as you call `mergeConfigFrom()` within the `boot()` method of the service provider (I actually think that may be incorrect behaviour.

Although within `ResponseCacheServiceProvider` you call `mergeConfigFrom` from within the 1register command (thats the correct place to do so from what i can see). The issue is I cannot over-ride/merge into this config from my package by calling `mergeConfigFrom` in my own service provider.

The base `ResponseCacheServiceProvider` provider takes precedence.

Currently we are getting our expected behaviour by doing the following in our service provider:

```php
    /**
     * Override response cache config
     *
     * @return void
     */
    protected function extendConfig()
    {    
        $source = realpath(__DIR__.'/../../config/responsecache.php');

        $config = $this->app['config']->get('responsecache', []);

        $this->app['config']->set('responsecache', array_merge($config, require $source));        
    }
```

**Comment by brendt** [comment]
Hi @andrewmclagan 

I gave this some thought and spoke it through in the office. As you say, the approach of fractal isn't the right one. We feel that it's best to stay as close to Laravel guidelines as possible here: let the end user configure dependant packages themselves. A good example is mail driver configuration in Laravel, where the developer must manually install the driver package he needs.

Whether you want to check for correctly installed dependant packages in your own service provider is up to you. I think that's the best advice I can give at this point, it's not a package's responsibility to enable itself to work with other third party packages.
