### ISSUE TITLE
Clear a specific cached single item on update/edit delete

### ISSUE THREAD

**Issue by simondavies** [spatie/laravel-responsecache#135]
Is it possible to target a specific cache file, so only it can be cleared?

Basically, take for example we have a blog.  

On creating a new blog, editing or deleting a blog, then when visiting the front end the new/edited etc blog can be seen.

But with the cache on I cannot see the new or edit the blog post and the deleted one is still listed.

So is it possible to call a clear function etc on the update/create or delete method, in order to view the new / edit content? Rather than clear the whole cache.

Hope this makes sense?

**Comment by freekmurze** [comment]
This currently isn't possible. Not all cache drivers provide tagging, so we need to always delete the entire cache.

**Comment by Yarandi** [comment]
Hi @freekmurze 
Do you already have this option : when a record update or delete from a model, delete the entire old cache and put new  updated cache on driver again?
