### ISSUE TITLE
Forgetting specific url isn't working

### ISSUE THREAD

**Issue by JoeyHoutenbos** [spatie/laravel-responsecache#142]
Hi,

I really like this package but the `ResponseCache::clear()` and `ResponseCache::forget(...)` don't seem to work for me. After some debugging I found out the forget-method isn't working, because the HTTP_HOST header in the used request isn't the same when caching the request and when clearing the cache for a specific url.

So in my routes file I added this route:
```php
Route::get('test', ['uses' => 'TestsController@index', 'as' => 'test.index'])->middleware('responseCache:15');
```

This is caching this route when I visit, but with a different hash than while forgetting this route. To forget the url I am using this:
```php
ResponseCache::forget('/test');
```

The `getHashFor`-method in the `RequestHasher` class is returning different results. This is because the `forget`-method is doing `$request = Request::create($uri);` for which the `HTTP_HOST` variable is `localhost`.
The `cacheResponse`-method in `ResponseCache` class is using the request where the `HTTP_HOST` variable is set to the one that's actually called. So when I am going to http://dev.local/test the HTTP_HOST is dev.local

I'll add a PR which should solve this problem.

**Comment by JoeyHoutenbos** [comment]
PR: https://github.com/spatie/laravel-responsecache/pull/143

**Comment by freekmurze** [comment]
We'll continue the conversation in #143
