### ISSUE TITLE
Issue with caching the query string parameters - version 4.4.3 

### ISSUE THREAD

**Issue by AsaadAbdo** [spatie/laravel-responsecache#144]
In the new version `getHashFor($request)` is now returning the same hash code for the responses no matter what you changed in the query string.

File: spatie/laravel-responsecache/src/RequestHasher.php
Line: 21

Wrong in v4.4.3:`"{$request->getPathInfo()}/{$request->getMethod()}/".$this->cacheProfile->cacheNameSuffix($request)`

Correct in v4.4.2:  `"{$request->getUri()}/{$request->getMethod()}/".$this->cacheProfile->cacheNameSuffix($request)`

**Comment by khanhvu14** [comment]
<img width="769" alt="screen shot 2018-09-26 at 3 15 02 pm" src="https://user-images.githubusercontent.com/4197632/46066537-01dcab80-c19f-11e8-82b1-86f4ab8aaa0a.png">
It's critical bug, plz revert this commit and wait next version when you add some new option in build hash request.

**Comment by JoeyHoutenbos** [comment]
@khanhvu14 making PR right now.

**Comment by khanhvu14** [comment]
@JoeyHoutenbos great, thanks

**Comment by AsaadAbdo** [comment]
@freekmurze can we have this PR merged please.

**Comment by AsaadAbdo** [comment]
Thanks @JoeyHoutenbos,  could you fix the test file as well `tests/ResponseHasherTest.php`.

@freekmurze could you get this PR merged please.

**Comment by AsaadAbdo** [comment]
Thanks @JoeyHoutenbos, 
@freekmurze could you get this PR merged please.

**Comment by freekmurze** [comment]
Merging...

**Comment by AndrijaAleksic** [comment]
I am using version 4.4.4 and it doesn't cache pages with different query string.
It only returns the first result.
Can you please fix this?
