### ISSUE TITLE
Request new upgrade for Laravel 5.7

### ISSUE THREAD

**Issue by quangvision** [spatie/laravel-responsecache#146]
Hello
  Can the author tells me if this current ResponseCache version supports Laravel 5.7? I am having problem with authentication using this package on Laravel 5.7. Thanks :)

**Comment by sebastiandedeyne** [comment]
This package support Laravel 5.7 since v4.4.2.

https://github.com/spatie/laravel-responsecache/releases/tag/4.4.2
