### ISSUE TITLE
I want to get the status code that I need to return after caching?

### ISSUE THREAD

**Issue by Ernest-wang** [spatie/laravel-responsecache#147]
The browser's return status is always 200 after reading the cache. How do you return 304?Or rewrite middleware?When I copied the middleware and rewrote it, it didn't work and the source code was fine

**Comment by belguinan** [comment]
Why do you need to have a cache for 304 status?
The package cache only a response only if it's successful or a redirection
You can check default cache profile in 

> Spatie\ResponseCache\CacheProfiles

 

But if you need!
You can override the cache profile as mentioned in the doc
https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile
