### ISSUE TITLE
Generate all available responses

### ISSUE THREAD

**Issue by belguinan** [spatie/laravel-responsecache#148]
Hello,
It would be great if we have a command to generate all cache for the website.
For exemple we setup a crontab everyday for clean and regenerate cache

**Comment by freekmurze** [comment]
I see a warming of the cache outside the scope of this package.  If you want this you could setup [our crawler](https://github.com/spatie/crawler) to crawl your entire site every day

**Comment by desaintflorent** [comment]
Hello @freekmurze , I'm trying to do the same.
I don't want to crawl the entire website just warming a couple of urls ( who are taking long time to load ) after a ResponseCache::clear().
I tried to use GuzzleHttp : 
```
$client = new \GuzzleHttp\Client();
$res = $client->get(url('/my-route/'));
```
And it's caching the response but only for GuzzleHttp request, when I'm back to my browser the page is not cached.
I tried also file_get_contents without any luck.

Do you have any idea how il could pre generate a response for an url without using a crawl package ?

Kind regards,
Thibaut
