### ISSUE TITLE
Question: on/off flag

### ISSUE THREAD

**Issue by dietervds** [spatie/laravel-responsecache#15]
Hi!

I'm looking into ResponseCache and it seems to be exactly what I needed, so a huge 'thanks!' to start off with.

I was wondering: is there a flag that can be set that easily enables or disables the cache? Like an environment variable where I can say RESPONSE_CACHE = false, just to easily check if an issue is cache-related or not?

Cheers!

**Comment by freekmurze** [comment]
Thank you for the kind words, I'm glad you like it!

In the config file there is [a master switch to enable/disable the cache](https://github.com/spatie/laravel-responsecache/blob/64bbf83/resources/config/laravel-responsecache.php#L8). So if you use that default config file you can use `RESPONSE_CACHE_ENABLED` in your env file.
