### ISSUE TITLE
Cache different query string

### ISSUE THREAD

**Issue by AndrijaAleksic** [spatie/laravel-responsecache#150]
I am using version 4.4.4 and it doesn't cache pages with different query string.
It only returns the first result.
Can you please fix this so that it cache for different query string?
Thanks

**Comment by freekmurze** [comment]
You can solve this by creating a your [own cache profile](https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile).

In that cache profile you can use `cacheNameSuffix` to differentiate a request from all other requests. You could opt to create an md5 from the serialized get parameters and return that.  That way you will get a different cache result based on the query parameters.

**Comment by AndrijaAleksic** [comment]
Thanks for your reply, Freek.
I have just created my own cache profile according to your advice.
But it still returns the same result.
`public function cacheNameSuffix(Request $request): string
    {
        if (\Auth::check()) {
            return md5(\Auth::user()->id.$request->fullUrl());
        }

        return md5($request->fullUrl());
    }`

**Comment by freekmurze** [comment]
Are you sure `fullUrl()` returns the url with the get parameters you are expecting?

If so could you submit a failing test for me to look at?

**Comment by AndrijaAleksic** [comment]
It was because of cache in redis.
After I updated it, it works well.
Thanks.
