### ISSUE TITLE
Laravel 5.5 -> 5.7 upgrade broke responsecache on multiple domains

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-responsecache#152]
I upgraded Laravel from 5.5 to 5.7 and now responsecache is not differentiating between different domains.
Caching test.com/ and test.net/ (separately) worked fine on Laravel 5.5. Now on Laravel 5.7 it's responding with the same cached page for both domains.

Is there a way to fix this with a setting or extending something, or is it just a bug?

**Comment by freekmurze** [comment]
I'm not using this package myself on an app that servers multiple domains, so I haven't been bitten by this. We try to not make any breaking changes. If you find were we made a breaking change, I'd be willing to accept a PR.

To explicitly differentiate between domains you could also [create a custom profile](https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile) and return a different `cacheNameSuffix` per domain.
