### ISSUE TITLE
Put cache after forgetting one specific cache in model observer 

### ISSUE THREAD

**Issue by Yarandi** [spatie/laravel-responsecache#154]
Hi all 
I have some problem to work with this package, the first is when we update one records of model we can't update exist cache , we should delete entire and put it in cache again. 

I have searched in issues and found that [#130](https://github.com/spatie/laravel-responsecache/issues/130) and I decide to use observer model and forget cache and create again,

Now I can forget cache with specific URL but  I can't create cache again.

I don't want create cache on middleware on Route because after each update it takes time. 

So, How should I do? 

If I can't Update a key in redis cache how can I should forget and create again in updated function on observer?

thanks in advance.

**Comment by freekmurze** [comment]
Currently the only way to clear the cache is to clear it. No other options are available nor planned. If you find a good way to update the cache, please PR it (with tests).
