### ISSUE TITLE
Multiple domains in the same project

### ISSUE THREAD

**Issue by renatosistemasvc** [spatie/laravel-responsecache#155]
I have a virtual store platform that is multi stores. That is, each store is differentiated by its domain. The laravel identifies the domain and mounts the store according to the domain.

I need to create the cache for each domain.

example: 

www.domain1.com.br -> creates cache pages for this domain
www.domain2.com.br -> creates cache pages for this domain

All domains go to the same project in laravel and in the controller that each domain is identified. I think I can solve the problem creating a custom cache profile. But I do not know how to do this. Is there an example or tutorial on how to create a custom profile to solve my problem?

**Comment by sebastiandedeyne** [comment]
To create a custom cache profile, you can refer to the [readme](https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile) and the existing `CacheAllSuccessfulGetRequests` class.

You'll probably need to generate your own cache name suffix to differentiate between the domains.

https://github.com/spatie/laravel-responsecache/blob/48588f7bb066776c31c68f9ca5ee6c4ee5281ee1/src/CacheProfiles/BaseCacheProfile.php#L26-L36
