### ISSUE TITLE
Dynamic web site...

### ISSUE THREAD

**Issue by SarajevoNo1** [spatie/laravel-responsecache#156]
Hello,

I am using laravel spatie response cache with my laravel app, when I add some new posts on my website, I dont see the new added post anywhere (on homepage, in posts index page listed).

Why I dont see new added posts?! And how to solve this.

I want to have cached homepage and all index pages but to see new added posts, articles etc?!

What is solution for this ?!

Thanks

**Comment by vesper8** [comment]
Are you invalidating the cache after adding a new post? You have to flush the cache or else it will keep showing the cached results.

try running
```
ResponseCache::clear();
```

in your controller after adding the new post
