### ISSUE TITLE
Response type in test

### ISSUE THREAD

**Issue by sdr0x07b6** [spatie/laravel-responsecache#158]
I'm installed this.
It is very fast!

However, the test may not pass.

```
// Pass
public function testFoo1() {
  $res = $this->get('/api/foo1');
  dump(get_class($res)); // "Illuminate\Foundation\Testing\TestResponse"
  $this->assertSame('Bar1', $res->getData()); // OK

  // Checking inside
  // Type of $res->baseResponse is "Illuminate\Http\JsonResponse"
}
```

```
// Failure
public function testFoo2() {
  $res = $this->get('/api/foo2');
  dump(get_class($res)); // "Illuminate\Foundation\Testing\TestResponse"
  $this->assertSame('Bar2', $res->getData()); // Method "getData" not exists...

  // Checking inside
  // type of $res->baseResponse is "Symfony\Component\HttpFoundation\Response"
}
```

`/api/foo2` is no problem with requests other than tests (curl, Postman etc).

In the test, why `Symfony\Component\HttpFoundation\Response` will be responded?
There is also a test in which `Illuminate\Http\JsonResponse` is responded.

How can I pass the test?

**Comment by freekmurze** [comment]
The upcoming `v6` of the package will always return an illuminate response. We'll release that version in the next few days. Upgrade to that version to fix this issue.
