### ISSUE TITLE
page tags with specific name

### ISSUE THREAD

**Issue by deepaksp** [spatie/laravel-responsecache#159]
Hi, Thank You for great lib.

i have recently started using this package in my project the only issue i have is not able to tag some pages with specific tag eg.

home page -> tag (home)
categories page -> tag (cat)
tag page -> tag (cat)
single data -> tag (view)

this way its easy to delete cache tags, though i have hacked service provider but i dont feel its right way to do it also laravel doesnt provide route name so i have to check url to assign tags 

here how i am doing it.

created my own service providers

changed where it assign tags

$tags = config('responsecache.cache_tag');
                    $tags = array_merge($tags, [$this->tagByUrl()]);
                    return $repository->tags($tags);

tagByUrl function check url and assign tag accordingly

I think if we can add another parameter in middleware this can be done without any major changes !
though i have not gone through source code yet.

**Comment by freekmurze** [comment]
Feel free to send a PR with tests and an updated readme.
