### ISSUE TITLE
PHP ^7.2 required, but Laravel allows ^7.1.3

### ISSUE THREAD

**Issue by matthewnessworthy** [spatie/laravel-responsecache#165]
PHP 7.2+ appears to be required by your `composer.json`, but there doesn't appear to be any PHP 7.2 features currently in use, nor does Laravel 5.8 require PHP 7.2.

Would it be possible to maintain parity with Laravel (`^7.1.3`), as the upgrade for the PHP isn't strictly necessary (and fairly time consuming right now)?

**Comment by freekmurze** [comment]
We'll continue the conversation in #166
