### ISSUE TITLE
Head's up on CORS

### ISSUE THREAD

**Issue by dietervds** [spatie/laravel-responsecache#17]
This is not really an issue, more of an head's up in case anyone has a similar problem in the future.

When we turned on our cache, we encountered issues with CORS.
Suddenly our SPA frontend had CORS errors when contacting the API where we implemented the cache. But not always.

Turns out that the problem is caused by the fact that the cache, when it caches the response to a request, it also caches the headers of that particular response.

Possible scenario: If it happens to be that the first request after the most recent cache flush is a component that doesn't require CORS, like another backend process, the response will be cached without CORS headers. If the SPA comes along after that, it gets a response without CORS headers even though it did ask for it.

Similarly: if one client queried that API as the first one after a flush, there will be CORS headers in the cache, but they might be specific to that client, so you might see an error like client1.company.com does not match client2.compamy.com origin. (client 2 receiving CORS headers that were specific for client 1)

I'm not sure how to mitigate this in a proper manner. Somehow keep CORS headers flowing freely but only cache the actual body of the request. But I'm not sure that that can be done in a satisfying manner.
The (not so great) mitigation is to always returns a CORS header with allowed-origin: \* , i.e. in your index.php, at the top, put
`header("Access-Control-Allow-Origin: *");`
This gets cached but will satisfy all clients. But sort of defeats the purpose of CORS protection I imagine.

Anyway, I hope this helps someone. If anyone has any clue on how to mitigate this in a better fashion, please let me know.

**Comment by sebastiandedeyne** [comment]
Interesting issue. Off the top of my head, I'd think the cleanest way to resolve this is implement your own version of the `ResponseCacheMiddleware`, where you'd always overwrite the CORS header with what you want. E.g.:

```php
public function handle(Request $request, Closure $next)
{
    if ($this->responseCache->hasCached($request)) {
        $response = $this->responseCache->getCachedResponseFor($request);
        // Modify response headers here...
        return $response
    }

    $response = $next($request);

    if ($this->responseCache->shouldCache($request, $response)) {
        $this->responseCache->cacheResponse($request, $response);
    }

    return $response;
}
```
(from https://github.com/spatie/laravel-responsecache/blob/master/src/Middlewares/ResponseCacheMiddleware.php)

If this would actually help you solve this issue, it'd be nice to split the `handle` method in multiple methods like `handleCachedResponse`, `cacheResponse`, etc... Would make overriding the middleware easier.

**Comment by dietervds** [comment]
I think that would be a clean solution indeed. I wonder if I can somehow call my CORS middleware from inside the ResponseCache middleware ^^ (I use the barryvdh/laravel-cors package). 

Although if the CORS rules are simple enough, one can add them there explicitly.

**Comment by themccallister** [comment]
Discovered this on an API project I was working on yesterday. Although I'm not sure if the solution is to write my own middleware or override the middleware provided by this package, or even how I should go about overriding it.

I'm going to give this some thought today and if I can find a solid solution I am going to post here.

**Comment by themccallister** [comment]
Alright, so here is a quick write up on solving this situation (if anyone stumbles across this issue)...

1. Follow the instructions for installation
2. Create a new middleware with the same name of `ResponseCacheMiddleware`. This allows you to override the Spatie provided middleware
3. Add the following code in the handle method of your middleware:

```php
$origins = 'localhost, www.domain.com';

if ($this->responseCache->hasCached($request)) {
    $response = $this->responseCache->getCachedResponseFor($request);
    $response->headers->set('Access-Control-Allow-Origin', $origins);
    return $response;
}

$response = $next($request);
$response->headers->set('Access-Control-Allow-Origin', $origins);

if ($this->responseCache->shouldCache($request, $response)) {
    $this->responseCache->cacheResponse($request, $response);
}

return $response;
```

Don't forget to inject the `ResponseClass` into the middleware constructor like so:

```php
/**
 * @var ResponseCache
 */
protected $responseCache;

/**
 * ApiResponseCache constructor.
 *
 * @param ResponseCache $responseCache
 */
public function __construct(ResponseCache $responseCache)
{
    $this->responseCache = $responseCache;
}
```

4. Enable the middleware in your `App\Http\Kernel.php` and apply where needed!

**Comment by freekmurze** [comment]
Nice solution, thanks for sharing!

 I'd accept a fully tested PR that adds this to the package. An `origins` key could be added to the config file. If it contains a value,  the extra headers should be set.

**Comment by freekmurze** [comment]
Closing this for now, like mentioned before, I'd accept a PR that adds a good solution to the package.
