### ISSUE TITLE
5.* tags point to master, 4.* tags point to v5 branch

### ISSUE THREAD

**Issue by willoller** [spatie/laravel-responsecache#172]
I am trying to use responsecache on Laravel 5.5
The docs indicate I should be on the v5 branch

Currently this is working for me:

`"spatie/laravel-responsecache": "v5.x-dev"`

Since this points to 48588f7 which allows 5.5.

This does not work:

`"spatie/laravel-responsecache": "~5.0.2"`

since 5* branches point to `master`, which requires 5.8+.

Maybe current v5 branch should be pointing to `master` and `48588f7` should be the tip of a branch called `v4`? Or maybe the current 5.* tags could instead be 8.* to match the minimum Laravel minor version? More likely: I just not seeing something?

**Comment by freekmurze** [comment]
Master points to the latest L5.8 v5 version. That seems fine.

If you want support for Laravel 5.5, use v4: https://github.com/spatie/laravel-responsecache/blob/4.4.5/composer.json
