### ISSUE TITLE
Forget specific url for all users

### ISSUE THREAD

**Issue by bernhardh** [spatie/laravel-responsecache#174]
Maybe I misunderstand something but is it correct, that `ResponseCache::forget("/url")` only deletes the cached url for the current logged in user, but not the "normal" ResponseCache or the ResponseCache for the other users?

The usecase / scenario is quite simple: I have a CMS where a user changes something. Now the system (a model observer) know the url of the model (for example an article) and calls 

```php
ResponseCache::forget($model->getUrl())
```

This deletes the cache for the specific url (which is what I want), but only for the current user (which is a bit weird). 

There should be something like `ResponseCache::forget($url, $forAllSuffixes = true)`

I know, that I can create an own CacheProfiles where I just could disable the suffix for the user, but I want to understand in why the default behavior is like it is or if I miss something?

**Comment by freekmurze** [comment]
I'm thinking `forget` should forget it for all users.

Could you PR a failing test for me to fix? If you already know a good fix, feel free to PR that too.

**Comment by bernhardh** [comment]
I am not really sure, how to write a test for it (how to easily simulate the user login for the request, which can be reproduced everywhere).

But the problem is quite simple (I think):

```php
    // 1) ResponseCache.php
    public function forget($uris): self
    {
        ....
        collect($uris)->each(function ($uri) {
            ...
            $hash = $this->hasher->getHashFor($request);
            if ($this->cache->has($hash)) {
            ...
            }
    }

    // 2) RequestHaser.php
    public function getHashFor(Request $request): string
    {
        return 'responsecache-'.md5(
            "{$request->getRequestUri()}/{$request->getMethod()}/".$this->cacheProfile->cacheNameSuffix($request)
        );
    }

   // 3) CacheProfiles/BaseCacheProfile.php
   public function cacheNameSuffix(Request $request): string
    {
        if (\Auth::check()) {
            return \Auth::user()->id;
        }

        return '';
    }
```

1) You are calling the `hasher->getHashFor` method, to check if there is already a hash (and you use this hash also for deleting). 
2) The hash is build by the url, the request method and **cacheProfile-Suffix**
3) The Suffix is the user id of current logged in user.

So if you call `forget` as a logged in user with the ID of `1`, you will `forget` the hash of "/url/GET/1", but the hash "/url/GET" or all other users will not be touched (like "/url/GET/2"). 

ATM, I have no general solution, I jused created a custom Profile, where I do not check if there is a user logged in (no need in my case, since I only need a global cache):

```php
class CacheAllSuccessfulGetRequestsIgnoreUser extends CacheAllSuccessfulGetRequests{
    public function cacheNameSuffix(Request $request): string {
        return '';
    }
}
```

**Comment by Rias500** [comment]
I've added a failing test in #184, though this seems hard to fix when you want to otherwise keep cached requests separate for users.

**Comment by freekmurze** [comment]
I'll make clear in the readme that clearing a specific url will not work when using a custom suffix.
