### ISSUE TITLE
Is It Possible To Cache Mobile & Desktop Version differently On Same URL

### ISSUE THREAD

**Issue by jahid56** [spatie/laravel-responsecache#175]
I want to Cache my Mobile & Desktop Version On same URL differently because my Mobile and Desktop Version layout is different and also the image of my page changes in Mobile, Desktop Version. Is It Possible To Cache Mobile & Desktop Version differently?

**Comment by freekmurze** [comment]
Create your own `CacheProfile` and make it return a different `cacheNameSuffix` depending on whether you're on mobile or on desktop.
