### ISSUE TITLE
Cache forget not working correctly 

### ISSUE THREAD

**Issue by jeffochoa** [spatie/laravel-responsecache#177]
I'm not 100% sure if this is an "issue" or maybe just missing documentation:

In the `ResponseCache::forget()` method you have the following:

```php
    public function forget($uris): self
    {
        $uris = is_array($uris) ? $uris : func_get_args();

        collect($uris)->each(function ($uri) {
            $request = Request::create($uri);
            $hash = $this->hasher->getHashFor($request);
            if ($this->cache->has($hash)) {
                $this->cache->forget($hash);
            }
        });

        return $this;
    }
```

When you use the `Request::cache()` method there (in the `forget()` method), for some reason the "request" host end up being "localhost" instead of your actual `env('APP_URL')` value.

So, when you try to "forget" a specific URI, the `Cache::has($hash)` will return`false`, because  the actual cached URL was, for instance, `www.your.app/some-uri`, but the `forget()` method is looking for `localhost/some-uri`.

According to the docs in the `read.me` file you can use the following to remove a response from the cache:

```php
// Forget one URI
ResponseCache::forget('/some-uri');
```

But now, after the update made here https://github.com/spatie/laravel-responsecache/commit/25bf283e8ff98265475543b4d383d28682b6a643 you actually have to use:

```php
// Forget one URI
ResponseCache::forget('www.your.app/some-uri');
```

Probably updating the docs would be the easiest solution, although I think that pull request I mentioned above could be a breaking change for some users.

**Comment by freekmurze** [comment]
This is indeed a bug introduced by the commit you mentioned. Ideally we should make `ResponseCache::forget('/some-uri');` work again. Feel free to submit a PR that fixes is. I'll try to take a look at this soon.
