### ISSUE TITLE
What does this package cache actually?

### ISSUE THREAD

**Issue by gfd6th** [spatie/laravel-responsecache#18]
I installed 'barryvdh/laravel-debugbar' package for debugging.

I could find the cached html in redis, but the debugbar indicated that the cached page still use the same partial views and querys as before.

So, what does exactly it cache?

**Comment by freekmurze** [comment]
It cache the entire response including the headers. I assume the debugbar uses headers to transmit info. Those headers are also being cached.

You can tell that a response is being cached if you see the `Laravel-responsecache` header appearing in the response.

**Comment by gfd6th** [comment]
Yes, it is. I could see `Laravel-responsecache` header in the response

**Comment by freekmurze** [comment]
Reopen if this is still causing problems.
