### ISSUE TITLE
Non-static method Spatie\ResponseCache\ResponseCache::flush() should not be called statically

### ISSUE THREAD

**Issue by amarsyla** [spatie/laravel-responsecache#19]
```
use Spatie\ResponseCache\ResponseCache;

ResponseCache::flush();
```

I am using the code above to clear my cache, but it gives the error in the title. What am I doing wrong, or is this a bug? I am using Laravel 5.2 and PHP7. I am trying to clear the cache after a user logs in.

Thanks.

**Comment by sebastiandedeyne** [comment]
The examples in the readme are using the facade, not the real class. Facades are registered in the root namespace:

```
use ResponseCache;

ResponseCache::flush();
```

https://laravel.com/docs/master/facades#using-facades
