### ISSUE TITLE
Problem on redirect

### ISSUE THREAD

**Issue by sdebacker** [spatie/laravel-responsecache#2]
Hope it's already ok to submit issues ?

I have this exception when I try to got to /admin, before I get redirected to /auth/login

ErrorException: Argument 2 passed to Spatie\ResponseCache\ResponseCache::cacheResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given

**Comment by freekmurze** [comment]
Yeah sure! Much appreciated. I'll fix that problem soon.

I still have to do some tests myself, so there's bound to be some more errors like the one you found.

**Comment by freekmurze** [comment]
Made some modifications. Though I haven't tested it in a full project, the unit tests indicate that this problem is solved.

**Comment by sdebacker** [comment]
Problem solved !
