### ISSUE TITLE
cache flusher flushes the whole cache of system

### ISSUE THREAD

**Issue by TheAliAbbasi** [spatie/laravel-responsecache#20]
so I was having problems with the system, scenario is as followed:
I have 2 routes under caching, one is my homepage, the other one are my posts. Whenever someone creates, modifies or deletes a post I flush the cache, which is redis. but whenever I flush the cache everyone get logged out, so I dug it up in the last week and found out that in ```Spatie\ResponseCache\ResponseCacheRepository``` line 67 you flushed the whole cache driver which is the same as my session driver (both on redis).

**Comment by TheAliAbbasi** [comment]
On second thoughts, you can do something like tagging your cached keys in order to flush only your key but not the whole system cache

**Comment by freekmurze** [comment]
As soon as tagged caches are available for every driver in Laravel (
https://twitter.com/freekmurze/status/752746891083976704), I'll update this
package.

Meanwhile you could use another driver like memcached for the responsecache
and redis for your system cache.

On Tuesday, 12 July 2016, TheAliAbbasi <notifications@github.com> wrote:

> On second thoughts, you can do something like tagging your cached keys in
> order to flush only your key but not the whole system cache
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spatie/laravel-responsecache/issues/20#issuecomment-231945886>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAdiDUkVT5Ih1paeMPSKXJwXEMv7ns00ks5qUy8bgaJpZM4JKEBY>
> .
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by TheAliAbbasi** [comment]
don't you think it's a little disturbing to flush the whole cache? maybe you can limit the cache drivers to the ones that support cache tags

**Comment by freekmurze** [comment]
There's only one that support tags currently and that's Memcached. As soon as all or most cache drivers support tagging, I'll update my package. 

In the meantime you could fork our code and adapt it to your specific needs.

**Comment by TheAliAbbasi** [comment]
i know that redis support this as well :+1:

**Comment by tomlankhorst** [comment]
@TheAliAbbasi 
Limit to taggable drivers and what's next?
Just make these features _optional_ and fallback to conservative behavior. 
I'll be evaluating options to add tags to this package and try to submit a PR.
