### ISSUE TITLE
Error comma on ResponseCache

### ISSUE THREAD

**Issue by mdeprezzo** [spatie/laravel-responsecache#216]
Hi,
in ResponseCache class, i got an error on line 61, for an extra comma

**Comment by freekmurze** [comment]
Please upgrade to PHP 7.3

**Comment by mdeprezzo** [comment]
@freekmurze i'm using homestead, with php 7.3.4, but i still got that error. Are there some config that i need to update, maybe in php.ini ?

**Comment by tehwave** [comment]
Sorry for bumping, @mdeprezzo, but did you find a solution? I too am experiencing this error on PHP v7.3.1 via Homestead. My understanding was that this is already supported in v7.3.

**Comment by mdeprezzo** [comment]
@tehwave Not yet. Maybe we need to update homestead to the last version.
