### ISSUE TITLE
Change middleware adoption strategy

### ISSUE THREAD

**Issue by michelecurletta** [spatie/laravel-responsecache#22]
This package is very helpful, but sometimes caching all request is not the best solutions.
So, if the most responses of an application shouldn't be cached, why don't register the "ResponseCacheMiddleware" like the "DoNotCacheResponseMiddleware", delegating to user the decision of which response/route should be cached?
Like as is, if user wants to cache only 3/4 responses, he should apply the "DoNotCacheResponseMiddleware" to all the other routes, instead of simply apply the "ResponseCacheMiddleware" to the routes he wants to cache.
I think the only thing should be done is preventing the "ResponseCacheMiddleware" to be pre-registered when installing the service provider.
@freekmurze what do you think about?

**Comment by freekmurze** [comment]
Hi, I think the way the package currently works is fine. The users of this package have enough options to customize the behaviour.
