### ISSUE TITLE
runningInConsole() and laravel-swoole

### ISSUE THREAD

**Issue by railken** [spatie/laravel-responsecache#220]
Hi,

is there a particular reason for which [this line](https://github.com/spatie/laravel-responsecache/blob/6.0.0/src/CacheProfiles/BaseCacheProfile.php#L39) exists?

```php
return app()->runningInConsole();
```

Shouldn't the check of the method be sufficient ([source](https://github.com/spatie/laravel-responsecache/blob/6.0.0/src/CacheProfiles/CacheAllSuccessfulGetRequests.php#L21))?
```php
return $request->isMethod('get');
```

I'm asking this because [laravel-swoole](https://github.com/swooletw/laravel-swoole) doesn't work in combination with this library because of the previous check `runningInConsole`

Thanks

**Comment by freekmurze** [comment]
`->isMethod('get')` returns `true` for console commands. We don't want to cache the response of console commands.

You can solve your issue by creating your own `CacheProfile` that doesn't extend `BaseCacheProfile`.
