### ISSUE TITLE
Skip returning cached response with specific header

### ISSUE THREAD

**Issue by ralbeary** [spatie/laravel-responsecache#223]
I setup this package in an API im making and is very impressive how easy is to return the responses very fast, thanks for that!

Also sometimes i need to request the original response and skip the cached version, how can i do this with out avoid flushing the cache? I try to make some conditional middleware loading but once the URL have been cached one time, i cant find the way to get a non-cached version.

**Comment by atymic** [comment]
You should create a custom cache profile, implementing the `CacheProfile` interface.
You can then check for the presence of a header and then response indicating it should be disabled.

https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile

**Comment by ralbeary** [comment]
@atymic Thanks for the response but finally im not going to use this package for the project.
