### ISSUE TITLE
ResponseCache::forget() not working if logged in as admin

### ISSUE THREAD

**Issue by fri3ndly** [spatie/laravel-responsecache#224]
First off, great package!

I'm trying to `ResponseCache::forget('/some-url')` from within our website admin area. The issue is that visiting the website will generate this public URI:

`/some-url/GET/`

whereas, because I am logged in as an admin and trying to edit a page (which once updated should forget the cache), the forget() URL that is being checked for when submitting this edited page is:

`/some-url/GET/1`

Making it hard to clear the public URL. I could add some logic in to remove this appended part of the URL but just wondering if there is a more elegant way to handle this?

Thank you 👍

**Comment by riasvdv** [comment]
Related to #209 and #174

**Comment by riasvdv** [comment]
We could solve this using [Cache tags](https://laravel.com/docs/master/cache#cache-tags) though they are not supported with the `file` and `database` cache stores. If/once they support cache tags, we'll implement a solution for this.

In the meantime you can either change the `useCacheNameSuffix()` function in your `CacheProfile` to not save a different cache store for each user (if this does not matter in your application) or you can generate the cache keys manually and clear them for each user in your system which is a bit more custom work.

**Comment by caocanhlinh** [comment]
I am interested in this issue
