### ISSUE TITLE
Any way to run some logic before returning the cached result?

### ISSUE THREAD

**Issue by fri3ndly** [spatie/laravel-responsecache#225]
If a page is cached of course the controller logic is skipped and the cached view is returned, however this means some of our tracking logic is also skipped which is skewing analytical data. Is there any way to pass a method to be called before returning the cached page?

**Comment by riasvdv** [comment]
You could probably solve this by creating a [Replacer](https://github.com/spatie/laravel-responsecache#creating-a-replacer) and adding some tracking logic there.

**Comment by atymic** [comment]
I think it would make more sense to trigger it on the `Spatie\ResponseCache\Events\ResponseCacheHit` event.
