### ISSUE TITLE
Readme cache response time incorrect

### ISSUE THREAD

**Issue by fri3ndly** [spatie/laravel-responsecache#226]
I think the documentation may be incorrect for showing 5 minutes and 10 minutes timings.

You have 5 minutes as `cacheResponse:300` and 10 minutes as `cacheResponse:600`

When I think they need to be

`cacheResponse:5` and 10 minutes as `cacheResponse:10`

because in the code see the `$lifetimeInMinutes` variable:
 ` public function cacheResponse(Request $request, Response $response, $lifetimeInMinutes = null)`

 This is also apparent based on my own testing where a value of `1` caches the page for 1 minute

**Comment by riasvdv** [comment]
@fri3ndly Which version of responsecache and Laravel are you on? The cache lifetimes have changed since Laravel 5.8 from minutes to seconds.

Our latest docs & package (>= v5.0.0) are correct by defining seconds

**Comment by fri3ndly** [comment]
Thanks @riasvdv - makes sense. Upgrading to 5.8 now and will manually set that version in composer as it defaults to ^4.4
