### ISSUE TITLE
Keys not showing up in redis

### ISSUE THREAD

**Issue by Suven** [spatie/laravel-responsecache#230]
Hey!

This is rather a question than a bug-report. We installed your middleware and it's working fine.

One thing we noticed though is that the keys this middleware uses to store responses in redis, are not showing up when doing a `KEYS *` in redis-cli. They are also not accessible via `GET cacheKey`. When using redis `monit` I do see that the middleware successfully stores an retreives its keys.

Do you have any idea why that might be / did you encounter this too?

I discovered this because I wanted to lookup how many responses are currently cached.

PS: I'm not using a cache tag and am using Laravel 5.8 in conjuction with responsecache 4.4

**Comment by atymic** [comment]
Is it possible your redis configuration is using a different redis database (ie n=1, rather than the default n=0).

If not, can you post your redis config?

**Comment by Suven** [comment]
Sorry for the late response.

It seems to be true that the difference resides in the redis database used. While everything that laravel caches is written to `0`, the response-cache-entries are written to db `1`.

The default config in laravel creates two database-connections for redis. Cache and default.. When using caching in laravel directly, it will use the default-connection while the response-cache uses the cache-connection. That's why it uses different dbs.. 

Thanks for your tip. (:
