### ISSUE TITLE
How do I cache `JsonResponse`?

### ISSUE THREAD

**Issue by sdr0x07b6** [spatie/laravel-responsecache#231]
## Restore the type when cached

Almost all of my API returns the `Illuminate\Http\JsonResponse` type.
The test code uses `JsonResponse::getData()` to check the content.

However, even though `laravel-responsecache` caches data of `JsonResponse` type, it always returns `Response` type when returning it.
So I don't pass the test. An error occurs because do not have the `getData()` method.

The middleware return type is set to `Response`.
`Middlewares\CacheResponse::handle(...): Response`
Can not restore type at cache time?

## ContentType to be cached by default

Also according to the document

> By default it will cache all successful get-requests that return text based content (such as html and json)

Is described as.

The default `CacheAllSuccessfulGetRequests::hasCacheableContentType()` checks `Str::startsWith($contentType, 'text')`.
This will not cache `application/json`.
I think that default should also include `application/json`.

---

- Laravel 5.8.28
- laravel-responsecache 6.0.1

Thanks😃

**Comment by atymic** [comment]
I agree. I made a custom cache profile for my application to add json. 
I would be happy to PR :)

**Comment by freekmurze** [comment]
Feel free to PR this. Make sure to add a test! 👍

**Comment by atymic** [comment]
PR open in #232
