### ISSUE TITLE
Do not cache a single route

### ISSUE THREAD

**Issue by eelcol** [spatie/laravel-responsecache#238]
The documentation seem to imply that it is possible to cache all requests by default, and not cache the routes which have the "doNotCacheResponse" middleware. However, when I add the CacheResponse middleware to the web-middleware in Kernel.php:

````
protected $middlewareGroups = [
        'web' => [
            //....//
            \Spatie\ResponseCache\Middlewares\CacheResponse::class,
        ],
    ];
````

And define a route in the routes file with the middleware "doNotCacheResponse", this route is still being cached:

````
Route::group(['middleware' => ['doNotCacheResponse']], function() {
    Route::get('test', 'Controller@test');
});
````

This route also has the "web" middleware. I have added the "doNotCacheResponse" to the routeMiddleware variable in Kernel.php. I would expect this route not to be cached because of the route-specific middleware. Is this the expected way this package is supposed to work? 

I have solved this by adding the "cacheResponse" middleware to all the routes I want to cache, and the "doNotCacheResponse" to all the routes I don't want to cache. But it would seem much nicer to just add the "cacheResponse" to the web-middleware so all routes will get cached by default, and only edit the routes I don't want to cache by adding the "doNotCacheResponse" middleware to those routes.

**Comment by vdbelt** [comment]
Have you cleared the cache before adding the doNotCacheResponse middleware? 

Once it is cached, it will continue to serve from cache.

**Comment by eelcol** [comment]
Thanks @vdbelt this was my problem. I expected the plugin never to use the cache when the middleware "doNotCacheResponse" was added, so this caused my confusion. Maybe a good idea to change the package, to not show a cached page when the doNotCacheResponse middleware is added, or create an extra middleware such as doNotReturnCachedResponse to achieve this?

**Comment by freekmurze** [comment]
Feel free to PR improvements to the readme.
