### ISSUE TITLE
Is it bad practice to use an observer over a trait?

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-responsecache#239]
The README mentions using a trait instead of [observers](https://laravel.com/docs/5.8/eloquent#observers). Isn't it possible to use observers instead? It seems to work fine in testing. :)

Thanks.

**Comment by vdbelt** [comment]
The README just provides an example that’s easy to read and implement (no need to register in a service provider). 

It’s up to your own personal preference really. Both approaches will work and there is nothing wrong with an observer implementation.

**Comment by francoism90** [comment]
@vdbelt OK, thanks. :)
