### ISSUE TITLE
Cron to cache

### ISSUE THREAD

**Issue by artisaninweb** [spatie/laravel-responsecache#240]
First i want to say i love this Laravel package!

The "problem" i've got is that the first visitor of the day is building the cache.
So i want to make a cron that will cache all pages.
I came up with this, is there another way to do this?

```php
public function handle()
  {
    Page::all()->each(function ($page) {
      ResponseCache::forget($page->url);

      $client = new GuzzleHttp\Client();
      $client->request('GET', env('APP_URL') . $page->url);
    });
  }
```

**Comment by atymic** [comment]
Consider using spatie's crawler library:
https://github.com/spatie/crawler

**Comment by artisaninweb** [comment]
Thanks.
Why install another package when the crawler also uses Guzzle as a client?

**Comment by atymic** [comment]
The crawler can run on a cron, and regenerate all the site pages automatically without you having to loop over every model.

The package doesn't have a feature to automatically update the cache if that's what you are asking.
