### ISSUE TITLE
Retrieve cache records by URL

### ISSUE THREAD

**Issue by Blum** [spatie/laravel-responsecache#242]
Hello, thank you for the awesome lib.

I think it would be great if there were some way to retrieve all the cache records for a certain URL no matter of the suffix. This will allow you to modify it or delete when certain events occur. Now we can just "forget" an URL, but only for no-suffix case.

Actually I made it by setting custom header in the cache record with the hashed URL and searching by it after that, but it is not good solution, slow and "expensive".

I know the lib implements Repository and you can not modify the structure of the repository itself, but.. it would be cool if someone comes up with something.

Thanks

**Comment by freekmurze** [comment]
Hi, 

The easiest way to support this, would be to have a support for allow to set a custom repository. In such repository you can then keep track of all the cache names used.

We currently have no need for this, and aren't going to invest time in it. But if you can achieve this in a simple way and PR this with updated test and docs, we'll consider merging it.

Another option for you would be to just fork the package, make the necessary adjustments in your own copy and roll with that.
