### ISSUE TITLE
Response type

### ISSUE THREAD

**Issue by sdr0x07b6** [spatie/laravel-responsecache#243]
Most of my APIs return data of type `Illuminate\Http\JsonResponse`.
So, even in API tests, the return value is retrieved with `getData()`.

```php
$res = $this->actingAs($user)->get('/api/myfunction');
$data = $res->getData();
```

However, in `laravel-responsecache`, it is converted into an array once when it is cached, and it is made` Illuminate\Http\Response` type when it is restored.
`laravel-responsecache/src/ResponseSerializer.php`

```php
use Illuminate\Http\Response as IlluminateResponse;

class ResponseSerializer
{
  protected function buildResponse(array $responseProperties): Response
  {
    ...

    return new IlluminateResponse(...);
  }
}
```

Therefore, the return value does not have a `getData()` method and the test fails.
Is there a way to solve this?

For example, select the type when restoring with `ResponseSerializer::buildResponse()`, or serialize as it is without arraying when caching...🤔

This question is a bit related to the question I asked before. #158

**Comment by sdr0x07b6** [comment]
If the current design cannot solve it, will it be the following method?

```php
class ResponseSerializer
{
  protected function getResponseData(Response $response): array
  {
    ...

    $content = $response->getContent();
    $type = self::RESPONSE_TYPE_NORMAL;
    $class = get_class($response); // Save class name

    return compact('statusCode', 'headers', 'content', 'type', 'class');
  }

  protected function buildResponse(array $responseProperties): Response
  {
    ...

    $class = $responseProperties['class'];

    // Restore as saved class
    return new $class($responseProperties['content'], $responseProperties['statusCode']);
  }
}
```

**Comment by atymic** [comment]
Personally, I don't see this a much of a problem. I'd assume in most tests you'd want the caching off (so you would get a `JsonResponse`) and in those where you specifically want to test the caching, you can check the `content-type` header and decode it.

If it's something that you do a lot, you could move it into your base test class(es).

**Comment by sdr0x07b6** [comment]
If my above code is not accepted,
What do you think of this approach?
The original policy is not changed. Customized only by those who need it.
Sorry for the long..

`config/responsecache.php`
```php
    /**
     * This class is responsible for generating a hash for a request. This hash
     * is used to look up an cached response.
     */
    'hasher' => \Spatie\ResponseCache\Hasher\DefaultHasher::class,

    /**
     * This class serializes cache data and expands it.
     * Serialization can save the data to be returned in an appropriate form.
     */
    'serializer' => \Spatie\ResponseCache\Serializer\DefaultSerializer::class,
];
```

```php
namespace Spatie\ResponseCache\Serializer;

interface Serializable
{
    public function serialize(Response $response): string

    public function unserialize(string $serializedResponse): Response
}
```

```php
namespace Spatie\ResponseCache\Serializer;

// Rename from ResponseSerializer
class DefaultSerializer implements Serializable
{
```

```php
use Spatie\ResponseCache\Serializer\Serializable;

class ResponseCacheServiceProvider extends ServiceProvider
{
    public function boot()
    {
        ...

        $this->app->bind(Serializable::class, function (Container $app) {
            return $app->make(config('responsecache.serializer'));
        });
```

```php
use Spatie\ResponseCache\Serializer\Serializable;

class ResponseCacheRepository
{
    public function __construct(Serializable $responseSerializer, Repository $cache)
    {
```

And...

```php
use Spatie\ResponseCache\Serializer\DefaultSerializer;

class MySerializer extends DefaultSerializer
{
    protected function getResponseData(Response $response): array
    {
        // Customize
    }

    protected function buildResponse(array $responseProperties): Response
    {
        // Customize
    }
```

**Comment by atymic** [comment]
I'm not actually the maintainer of the package. I'd see what @freekmurze thinks, and/or create PR with the proposed changes :)

**Comment by freekmurze** [comment]
Please send a PR with update tests and readme that makes the serializer more configurable. Love the idea the people could just specify one in the config file that adheres to an interface 👍
