### ISSUE TITLE
Include Cache-Control headers based on the TTL

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/laravel-responsecache#25]
Would it be possible to return `Cache-Control` headers based on the time/expiration/TTL the user has configured?

It may be out of the scope of this package, but if the Laravel app is able to set the correct headers, it can use 2 important caches: client-side cache (browser) + server-side cache (PHP).

In addition, if you are able to put Varnish on your server, it will listen & adhere to the `Cache-Control` header and obey that `public` vs `private` marker and cache it for the `max-age` duration.

Here's what it looks like:

```
  header("Cache-Control: public, max-age=900");
```

Take care,

Mattias

**Comment by freekmurze** [comment]
That's an excellent suggestion.

I'd accept a PR that adds this to the package. On first thought headers will have to be added somewhere in this class: https://github.com/spatie/laravel-responsecache/blob/master/src/Middlewares/ResponseCacheMiddleware.php

**Comment by freekmurze** [comment]
Closing this for now. If you're reading this and interested in the feature, I'd accept a fully tested PR.

**Comment by AlbinoDrought** [comment]
If it helps anyone, this quick wrapper works for my usecase:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Spatie\ResponseCache\Middlewares\CacheResponse;
use Symfony\Component\HttpFoundation\Response;

class PublicCache extends CacheResponse
{
    public function handle(Request $request, Closure $next, ...$args): Response
    {
        $response = parent::handle($request, $next, ...$args);
        $response->headers->addCacheControlDirective('public');

        $lifetimeInSeconds = $this->getLifetime($args);
        if ($lifetimeInSeconds !== null) {
            $response->headers->addCacheControlDirective('max-age', $lifetimeInSeconds);
        }

        return $response;
    }
}
```

Result looks something like:

```http
HTTP/1.1 200 OK
Server: nginx/1.14.2
Content-Type: application/json
Connection: keep-alive
Cache-Control: max-age=1800, public
Date: Wed, 05 Aug 2020 16:52:18 GMT
```
