### ISSUE TITLE
Is ResponseCache::clear() the same as Cache::tags()->flush() ?

### ISSUE THREAD

**Issue by sdr0x07b6** [spatie/laravel-responsecache#250]
`routes/api.php`
```php
Route::get('/users', UserIndexAction::class)->middleware(['cacheResponse:users']);
Route::get('/products', ProductIndexAction::class)->middleware(['cacheResponse:products']);
```

This test code succeeds.
```php
use Config;
use Illuminate\Support\Facades\Cache;
use Spatie\ResponseCache\Facades\ResponseCache;

/**
  * @test
  */
public function clearByTag() {
  $header = Config::get('responsecache.cache_time_header_name');

  // Ignore the CACHE_DRIVER setting in phpunit.xml and use Redis
  Config::set('cache.default', 'redis');


  // Clear all cache as initialization
  ResponseCache::clear();

  // Create a cache for "users" and "products"
  $this->get('/api/users');
  $this->get('/api/products');

  // Delete the "users" cache by tag
  // ResponseCache::clear(['users']); // Fail
  Cache::tags('users')->flush(); // Pass

  // Response is only cached for "products"
  $this->get('/api/users')->assertHeaderMissing($header);
  $this->get('/api/products')->assertHeader($header);
}
```

The README explains that:
>Note that this uses Laravel's built in cache tags functionality, meaning routes can also be cleared in the usual way:
>Cache::tags('special')->flush();

However, changing `Cache::tags(['users'])->flush();` to `ResponseCache::clear(['users']);` will fail.
Do these two cache deletes work the same way?

**Comment by sdr0x07b6** [comment]
Hi, @freekmurze

I have prepared a reproduction project that allows you to easily check the test results.
Sorry to trouble you, try to run it.

**The only note:**
Redis must be running because it uses a tagged cache.
If you use memcached, please change Laravel settings.


```sh
$ git clone https://github.com/sdr0x07b6/responsecache-test20190906.git
$ cd responsecache-test20190906
$ composer install
$ composer test
```
The test should succeed.
Now open `ExampleTest.php` and change the way the cache is deleted.

```sh
$ open tests/Feature/ExampleTest.php
```

```php
// Replacing comment out

ResponseCache::clear(['users']); // Fail
// Cache::tags('users')->flush(); // Pass
```
```sh
$ composer test
```

The test should fail.
These are the same features but why do they fail?

Thanks.

**Comment by atymic** [comment]
Ok, i've done some investigation.

It seems that the issue is that `ResponseCache::clear` is clearing the entire cache. It calls the `clear ` method on the cache, which is flushing the redis DB (ie clearing unrelated keys)

```
/**
     * {@inheritdoc}
     */
    public function clear()
    {
        return $this->store->flush(); // Runs flushdb on redis
    }
```

It's very confusing because the [laravel docs](https://laravel.com/docs/5.8/cache) says:

> Flushing the cache does not respect the cache prefix and will remove all entries from the cache. Consider this carefully when clearing a cache which is shared by other applications.

But for the the tagged caches, `flush` only clears those tags:

> You may flush all items that are assigned a tag or list of tags. For example, this statement would remove all caches tagged with either people, authors, or both. So, both Anne and John would be removed from the cache

TD;LR: `clear()` flushes the entire redis DB, `flush()` only clears the tags.

I'll create a PR to switch to the `flush` method.

**Comment by atymic** [comment]
Further issues:

Currently in our tests, the tagged routes are inside a route group that has the cache response middleware

This means they are being cached twice
https://github.com/spatie/laravel-responsecache/blob/master/tests/TestCase.php#L136-L144

**Comment by atymic** [comment]
I'll do some further investigation later.

**Comment by freekmurze** [comment]
Thank you for your work on this @atymic 👍

**Comment by atymic** [comment]
No worries. Changing to use the `flush` method broke a bunch of tests, and I ran of out debugging time. Will try and PR soon.

**Comment by paulhuisman** [comment]
Any updates on this?

**Comment by matthewscalf** [comment]
Any news on this @atymic ? Definitely need that switched back to cache flush.

**Comment by atymic** [comment]
To be honest, i haven't look since. I've been pretty busy and haven't had a chance (and the project is using cloudfront now).

**Comment by zlanich** [comment]
It appears this was fixed at some point: 
```php
public function clear(array $tags = [])
{
  $this->taggedCache($tags)->clear();
}
```
