### ISSUE TITLE
Console command 'clear' does not work

### ISSUE THREAD

**Issue by tekord** [spatie/laravel-responsecache#252]
The responsecache package successfully installed, I see a response header with cache timestamp. But when I want to clear the whole cache, I execute the command `php artisan responsecache:clear`, then got the message `Response cache cleared!`, but nothing cleared. I see exactly the same cache timestamp in a response header.

My configuration file:

```
	'enabled' => env('RESPONSE_CACHE_ENABLED', true),
	'cache_profile' => Spatie\ResponseCache\CacheProfiles\CacheAllSuccessfulGetRequests::class,
	'cache_lifetime_in_seconds' => env('RESPONSE_CACHE_LIFETIME', 60 * 60 * 24 * 7),
	'add_cache_time_header' => true, // always true
	'cache_time_header_name' => env('RESPONSE_CACHE_HEADER_NAME', 'laravel-responsecache'),
	'cache_store' => env('RESPONSE_CACHE_DRIVER', 'file'),
	'replacers' => [
		\Spatie\ResponseCache\Replacers\CsrfTokenReplacer::class,
	],
	'cache_tag' => '',
	'hasher' => \Spatie\ResponseCache\Hasher\DefaultHasher::class,
```

RESPONSE_CACHE_DRIVER=file

PHP 7.3, Laravel 5.8.*

**Comment by tekord** [comment]
I tried to clear via `artisan tinker`. That's what I got (a lot of warnings):

```
PHP Warning:  unlink(/var/www/project.www/storage/framework/cache/data/ff/1f/ff1f5df1bce4936f645258699a7419dbbb493b5d): Permission denied in /var/www/project.www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 207
PHP Warning:  rmdir(/var/www/project.www/storage/framework/cache/data/ff/1f): Directory not empty in /var/www/project.www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 572
```

Seems like `responsecache:clear` just ignoring the warnings. Also, seems like it does not consider cache folders can be occupied by other cache entries (which is my case).

**Comment by tekord** [comment]
Solved. This issue appeared due to wrong permissions. But I think the `responsecache:clear ` command should be more verbose and display warnings.

**Comment by atymic** [comment]
The command just call clear on whichever cache you set up
https://github.com/spatie/laravel-responsecache/blob/master/src/Commands/ClearCommand.php#L20

You only see the warnings in tinker because they don't show when you run commands.

**Comment by tekord** [comment]
@atymic I see. Thank you!
