### ISSUE TITLE
Getting an error in v6.3.0

### ISSUE THREAD

**Issue by paulhuisman** [spatie/laravel-responsecache#256]
Hi there,

I'm getting a syntax error in the latest version (6.3.0):

`ERROR: syntax error, unexpected ')' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected ')' at /home/forge/test.com/releases/20190924094403/vendor/spatie/laravel-responsecache/src/ResponseCache.php:60)`

**Comment by freekmurze** [comment]
Make sure you are running PHP 7.3.

**Comment by paulhuisman** [comment]
That's weird, am running `PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1` (on Forge)

**Comment by freekmurze** [comment]
The tests confirm that the package is working fine. If you find that the package is in error, feel free to open up an new issue or PR the fix 👍

**Comment by paulhuisman** [comment]
Opened a new PR for this: https://github.com/spatie/laravel-responsecache/pull/257
