### ISSUE TITLE
ESI integration? Integration with dynamic parts

### ISSUE THREAD

**Issue by josearagon** [spatie/laravel-responsecache#259]
Hello!

Sorry for write this message here, but... it have ESI integration? 
Our site has dynamic parts: last posts, promotions... how can we integrate it with this package? Any similar experience? We can not use ajax call because the content is important for SEO.

Thanks a lot!

**Comment by freekmurze** [comment]
There's no real ESI support, but we have replacers: https://github.com/spatie/laravel-responsecache#creating-a-replacer

That might help you.

**Comment by josearagon** [comment]
It sound really good!!! 

Thanks a lot!!
