### ISSUE TITLE
Not working on HTML responses

### ISSUE THREAD

**Issue by teamhoodin** [spatie/laravel-responsecache#26]
I'm having an issue whereby my API-endpoints are being cached as expected but my HTML views are not. I've not disabled them using the doNotCacheResponse middleware, and I'm sure what I'm seeing is correct as I've enabled the addCacheTimeHeader setting, and it shows on the API-routes, but not on any others. I think it must be in what I'm returning, so I'll include my controller responses here. Any idea what I'm doing wrong?

API:
`return response()->json($output);`

HTML:
`return view('general.about');`

**Comment by freekmurze** [comment]
I'm not sure what is going wrong in your app.

I suggest you take a look at `ResponseCacheMiddleware.php` to figure out what goes wrong. Try adding some `dd()` statements to determine what it happening.

**Comment by teamhoodin** [comment]
Thanks for the response. I've tested a bit, and the difference is that on the non-working requests line 33 in the `ResponseCacheMiddleware.php` 
`$response = $next($request);`
returns the response directly, so I can't dd anything after that. On the api-endpoints which are cached correctly I can `dd()` afterwards. The Closure and the Request being fed in look similar in structure, so not sure what the difference could be.

**Comment by teamhoodin** [comment]
Oddly enough it's now started working without touching it. Very strange! Thanks for making this, it's very cool! :)
