### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by germansango** [spatie/laravel-responsecache#260]
Good afternoon, I wanted to use this excellent package, and I can not use it in version 6 of Laravel asking me to install Laravel 5.8. Will this package have support for Laravel 6?
![error-laravel](https://user-images.githubusercontent.com/13042916/67106557-7ca0ac00-f190-11e9-887d-8a3dcd7f9043.png)

**Comment by mrk-j** [comment]
You should update to the latest version of this package. Laravel 6 is supported since `v6.3.0`: https://github.com/spatie/laravel-responsecache/blob/6.3.0/composer.json#L24

**Comment by nafplann** [comment]
is laravel 6.2 supported yet?
