### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by Hamdan13** [spatie/laravel-responsecache#261]
Hii..
I'm use this package in local Homestead everything work fine!
but when i upload my project to live server (Debian with Aphace 2.4.24 PHP 7.3) showing error **ReflectionException
Class Spatie\ResponseCache\ResponseCache does not exist
Previous exceptions**.
Anyone can help me?
Thanks Advance..
<img width="1277" alt="Screenshot 2019-11-05 at 11 31 27" src="https://user-images.githubusercontent.com/6159896/68178871-1a351180-ffc0-11e9-8fc2-ccc4e9f1e629.png">

**Comment by nighon** [comment]
Please confirm you are using **php 7.3**

**Comment by nighon** [comment]
#237

**Comment by danielclark0310** [comment]
I have seen the same issue. Did not occur locally. I am using PHP 7.3.11 with Laravel 6.5.1.

**Comment by Hamdan13** [comment]
> Please confirm you are using **php 7.3**

i see...
my problem is php vesion..
thank you very much for helping :D
