### ISSUE TITLE
Replacer is not working when cache expires

### ISSUE THREAD

**Issue by chojnicki** [spatie/laravel-responsecache#262]
Simple scenario. I want to cache homepage. Let's give it just few seconds cache to test timings.

`Route::get('/', 'SomeController@index')->middleware('cacheResponse:5');`

CSRF token should be unique so let`s use replacers from docs.

`<meta name="csrf-token" content="<laravel-responsecache-csrf-token-here>">`

Cool. Now let's open homepage in browser and check source:
First entry - does not work:
`<meta name="csrf-token" content="<laravel-responsecache-csrf-token-here>">`
Refresh - success: 
`<meta name="csrf-token" content="MsHDyCVQELtzH0ydGHeJnZr5pJY2mZRx9wjlm1Ah">`
Refresh again after few seconds - damn...:
 `<meta name="csrf-token" content="<laravel-responsecache-csrf-token-here>">`
Refresh immediately:
`<meta name="csrf-token" content="MsHDyCVQELtzH0ydGHeJnZr5pJY2mZRx9wjlm1Ah">`

What is going on? It looks like replacer is working only on already cached response, but not on first visit and after expiration.

**Comment by riasvdv** [comment]
To show a csrf_token you should still just use `{{ csrf_token() }}` in your view, don't use the replaced tag directly, the Replacer will take care of replacing the actual token with a placeholder in the cache.

**Comment by chojnicki** [comment]
Oooh now it makes sense. Thanks!
