### ISSUE TITLE
Typed property error

### ISSUE THREAD

**Issue by sirvantos** [spatie/laravel-responsecache#266]
Hello guys.

probably it is php7.4 / vapor issue but let you know that i faced with a very starnge error on AWS Lambda

Spatie\ResponseCache\ResponseCacheRepository::$cache must be unknown or null, Illuminate\Cache\Repository used

"file": "/var/task/vendor/spatie/laravel-responsecache/src/ResponseCacheRepository.php:17",

code below:

https://github.com/spatie/laravel-responsecache/blob/6.4.0/src/ResponseCacheRepository.php

sometimes code works correct, sometimes not.... 

I have not found any description for error above.

**Comment by freekmurze** [comment]
Closing this as the error is probably related to your environment and not the code of this package.

If it turns out the package is the culprit, I'd welcome a PR that fixes your problem.
