### ISSUE TITLE
Update Responsecache

### ISSUE THREAD

**Issue by RuchitaCrawl** [spatie/laravel-responsecache#269]
Hi @freekmurze ,
Thanks for this awesome package.

I want to update the cache when it has new data/record in database.

Ex.
I have an API, which call by mobile app. So when they do first API call using GET request then I have to store the DB data in the cache.
suppose, In db.users table  i have 3 records, so any get request comes then it will stores those 3 records in the cache. 

Now suppose from the web, admin added more users ( added 2 users ), then whenever request comes from mobile app then in cache it have to update cache response with the 2 new users.
In response we have to give total 5 records.

Currently I'm clearing the cache whenever new records added in the DB,  so instead of clearing the cache is it possible to update the cache?

PHP Version: 7.3
Package Version: "spatie/laravel-responsecache": "^6.0"
Laravel Version: 5.8

Thank You :)

**Comment by freekmurze** [comment]
There is no way to update the response cache. Maybe tags can help you for your use case? https://github.com/spatie/laravel-responsecache#using-tags
