### ISSUE TITLE
Would be amazing if it supported Inertia.js

### ISSUE THREAD

**Issue by tanthammar** [spatie/laravel-responsecache#272]
Is it possible to tweak the settings to support Inertia-vue/Inertia-laravel?
As it is now, the response triggers Inertia to open the response in its Modal.

**Comment by freekmurze** [comment]
Feel free to PR improvements in this area.

**Comment by sebastiandedeyne** [comment]
I think a minor cache profile tweak should do it.

1) Extend the `Spatie\ResponseCache\CacheProfiles\CacheAllSuccessfulGetRequests` class

2) Override the `useCacheNameSuffix` method to include the type of Inertia request (HTML or JSON)

```php
public function useCacheNameSuffix(Request $request)
{
    return Request::inertia() ? 'inertia' : 'html';
}
```

3) Set the extended class as the cache profile in `config/responsecache.php`

```php
return [
    /*
     *  The given class will determinate if a request should be cached. The
     *  default class will cache all successful GET-requests.
     *
     *  You can provide your own class given that it implements the
     *  CacheProfile interface.
     */
    'cache_profile' => App\CacheAllSuccessfulGetRequests::class,
];
```
