### ISSUE TITLE
How can I have general observer or trait that clears cached responses on create, update, delete?

### ISSUE THREAD

**Issue by nekromoff** [spatie/laravel-responsecache#273]
this is not clear in readme:
https://github.com/spatie/laravel-responsecache#using-model-events

What should one do exactly to implement this?

**Comment by freekmurze** [comment]
Take a look at model events in the Laravel docs: you can use these to perform some extra logic, in this case clearing out the cache, when certain model events happen.

https://laravel.com/docs/master/eloquent#events

**Comment by nekromoff** [comment]
Adding info on how to implement it for someone, who looks for the same thing:

create file `app/Traits/ClearsResponseCache.php`:
```
<?php

namespace App\Traits;

use Spatie\ResponseCache\Facades\ResponseCache;

trait ClearsResponseCache
{
    public static function bootClearsResponseCache()
    {
        static::created(function ($model) {
            ResponseCache::clear();
        });

        static::updated(function ($model) {
            ResponseCache::clear();
        });

        static::deleted(function ($model) {
            ResponseCache::clear();
        });
    }
}
```

Add this trait to all the models you want to cache and clear on edit/update/delete:
e.g. model `app/Employee.php`:
Add line:
```
use App\Traits\ClearsResponseCache;
```
and include the trait in the model class like this:
```
class Employee extends Model
{
    use ClearsResponseCache;
```
