### ISSUE TITLE
Can't write to storage

### ISSUE THREAD

**Issue by m-bosch** [spatie/laravel-responsecache#274]
Hi there,

We are using your package on a website with a high visit ratio. About three times a week we get the following error randomly. We tried to figuring out what the problem is but we can't trigger it manually.

`file_put_contents(/home/user/domains/domain.nl/public_html/releases/20200113-151943-master/storage/framework/cache/data/84/09/8409ffaffb2596475ca7c732eaae16e35e4d5cde): failed to open stream: No such file or directory`

Last occurance: `2020-01-19 07:00:34`

It seems like the file can't be written, but it isn't a storage quota issue. 

Maybe more people have similar issues?

**Comment by LukeTowers** [comment]
@m-bosch I'm not sure this is related to this specific package, I think it might be a generic issue with using the `file` cache driver for high volume Laravel based sites. I maintain an @octobercms based site with a fairly high amount of visits and every once in a while (similar timing to you actually) we'll get issues like the following:

> Warning: fopen(/storage/framework/cache/16/e9/16e944615007eef0bb9bcd0b919492cf08f066c0): failed to open stream: No such file or directory

What's bizarre is that it is triggered by the Cache `file` driver attempting to load from the cache with `sharedGet()` here: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/Filesystem.php#L54; however the call to `sharedGet()` is wrapped in an `isFile()` check which should tell the system whether or not the file exists before opening it: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/Filesystem.php#L37-L39.

It seems to be a very obscure race condition of some sort, I'd much appreciate anyone's insight on the matter. @freekmurze have you ever come across anything similar?

**Comment by freekmurze** [comment]
Haven't gotten this error myself yet.

**Comment by Tklaversma** [comment]
@LukeTowers I'm using database cache. 
@freekmurze I use Laravel 7 (default install) + I've followed the readme. So nothing special. 

I just want to replace HTML code instead of textual content.

For its working, but without the opening and closing first and last char.

Can you mimic my issue?
