### ISSUE TITLE
Why was support dropped for PHP 7.2 and 7.3?

### ISSUE THREAD

**Issue by tsjason** [spatie/laravel-responsecache#275]
PHP 7.2 and 7.3 are both still supported by PHP and Laravel 6. Why was support dropped for them for this package? It's a bit inconvenient because now it's impossible to use this package with Laravel 6.0 and PHP 7.2. Is there PHP 7.4 specific functionality that is required for this package to work?

**Comment by freekmurze** [comment]
For all our projects we now use PHP 7.4. We could use some PHP 7.4 features in this package.

If you're using an older version of PHP 7.3, there's no problem, composer will pick the right version for you.

**Comment by tsjason** [comment]
But there is no way to use Laravel 6.0, PHP 7.2 and this package. I'm wondering if there is an actual reason, or if it was just a decision you made to drop support for that configuration.

**Comment by smknstd** [comment]
> If you're using an older version of PHP 7.3, there's no problem, composer will pick the right version for you.

Not sure about that.

```
    "require": {
        "php": "^7.4",
        ...
    },
```
makes composer say:

```
Problem 1
    - spatie/laravel-responsecache 6.4.0 requires php ^7.4 -> your PHP version (7.2.24) does not satisfy that requirement.
```

That's what I get and it makes sense to me.

**Comment by freekmurze** [comment]
Please require v6.2: it allows 7.3 and Laravel 6.

https://github.com/spatie/laravel-responsecache/blob/6.2.0/composer.json

For Laravel 6 and PHP 7.2 you're out of luck. If you want that, fork this package and make the necessary adjustments in your own copy.

**Comment by rdgout** [comment]
@freekmurze Can you not make a backport so we can atleast use 6.2 with Laravel 7? 
Right now this package is holding back our upgrade to Laravel 7 since only the newer versions, which require PHP 7.4, have gotten the simple composer upgrade to Laravel 7 support.
Due to an older project running statamic, which is running on Laravel 5.1, we cannot upgrade to PHP 7.4 right now.

**Comment by freekmurze** [comment]
Ok, I'll create a version based of 6.2 with Laravel 7 support soon.
