### ISSUE TITLE
Option to specify tags on Cache Profile

### ISSUE THREAD

**Issue by LasseRafn** [spatie/laravel-responsecache#276]
I'm thinking making a PR to allow specifying some tags to include in the cache profile automatically (e.g user id) to make it easier to clear a specific users cache, rather than for everyone.

Just wanted to know if this would be considered merging? — alternatively I'll fork and use that, but maybe worth adding in main repo?

**Comment by freekmurze** [comment]
If the code is easy to understand, well documented and tested, we'll consider merging it in!

**Comment by vonec** [comment]
+1 waiting for that
