### ISSUE TITLE
Variables in URL are not cached properly

### ISSUE THREAD

**Issue by alvinbakker** [spatie/laravel-responsecache#28]
I have a module with custom pagination. The URL will be something like /publications and the next overview will be /publications?start=20

As I have caching on for everything (except the backend), /publications is cached and when going to ?start=20 I get the cache of the previous page.

Is there a way to exclude these? Something like if URL contains ? do not cache...?

**Comment by juanvillegas** [comment]
Actually, it should cache both /publications and /publications?start=20, but as separate pages, as they are effectively different pages.
I wouldn't use a numeric index there though. Suppose you cache start=20, and then create some more posts in your blog. The page will become quickly outdated. Rather, you may use some sort of hash or uuuid to refer to the post start/end position.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes this.

**Comment by tommymarshall** [comment]
I wrote the tests for this, and... the tests passed. I believe this already works.

**Comment by kmccarth** [comment]
@tommymarshall prove it, haha, i just google'd this exactly issue and would love to know more

**Comment by freekmurze** [comment]
I'm also think this already works. If not, please submit a failing test
