### ISSUE TITLE
tell its working on production redis

### ISSUE THREAD

**Issue by FutureFutureTo** [spatie/laravel-responsecache#283]
Hey there,

Was just wondering if there were an easy way to determine whether or not this is caching through redis on production?

**Comment by ultrono** [comment]
The response time decreases drastically. Try toggling the `RESPONSE_CACHE_ENABLED` setting. Whilst enabled, with the Redis cache driver, I'm seeing response times of <100 ms in some cases.

Additionally you should be able to see a response header set by the package i.e. the value of `cache_time_header_name` (see [here](https://github.com/spatie/laravel-responsecache/blob/master/config/responsecache.php#L35) and [here](https://github.com/spatie/laravel-responsecache/blob/master/src/ResponseCache.php#L79-L89)).
