### ISSUE TITLE
Error in composer require with "laravel/framework": "^7.0"

### ISSUE THREAD

**Issue by filippolcr** [spatie/laravel-responsecache#291]
🙌 Just trying to use this package with Laravel 7.

After `composer require spatie/laravel-responsecache`

I encounter the error 🤔:

>  Problem 1
>    - Installation request for spatie/laravel-responsecache ^5.0 -> satisfiable by spatie/laravel-responsecache[5.0.0, 5.0.1, 5.0.2, 5.0.3, v5.x-dev].
>    - Can only install one of: laravel/framework[v7.7.1, 5.8.x-dev].
>    - Can only install one of: laravel/framework[5.8.x-dev, v7.7.1].
>    - Can only install one of: laravel/framework[5.8.x-dev, v7.7.1].
>    - Conclusion: install laravel/framework 5.8.x-dev
>    - Installation request for laravel/framework (locked at v7.7.1, required as ^7.0) -> satisfiable by laravel/framework[v7.7.1].`

The composer.json file contains:

> "php": "^7.2",
> "laravel/framework": "^7.0"

So, I have tryed to composer update Laravel to v7.7.1 but I encountered the same error message

> Problem 1
>    - Installation request for spatie/laravel-responsecache ^5.0 -> satisfiable by spatie/laravel-responsecache[5.0.0, 5.0.1, 5.0.2, 5.0.3, v5.x-dev].
>    - Can only install one of: laravel/framework[v7.7.1, 5.8.x-dev].
>    - Can only install one of: laravel/framework[5.8.x-dev, v7.7.1].
>    - Can only install one of: laravel/framework[5.8.x-dev, v7.7.1].
>    - Conclusion: install laravel/framework 5.8.x-dev
>    - Installation request for laravel/framework v7.7.1 -> satisfiable by laravel/framework[v7.7.1].

**Comment by freekmurze** [comment]
Either upgrade to php 7.4 or use an older version of the package.
