### ISSUE TITLE
Version incompatibility with Laravel

### ISSUE THREAD

**Issue by mdelariva** [spatie/laravel-responsecache#292]
First of all, sorry if this is not the place to make this comment but I couldn't figure out how to reach to you with this issue:
I have just installed Laravel 7 as the documentation requires, and is working fine using PHP 7.3, but the new versions of this package (>6.3) requires PHP 7.4. So, I tried to install the 6.3 version that only requires PHP 7.3, but it can't handle Laravel 7. 
So, I'm trapped and I can't use this (awesome) package because I can't update PHP in my server. Any possible solution for my problem?
Thanks!

**Comment by freekmurze** [comment]
Please fork the package and make the modifications you need.
