### ISSUE TITLE
Delete one page from cache [wish]

### ISSUE THREAD

**Issue by droptable-ru** [spatie/laravel-responsecache#3]
I think must be method for delete one page from cache like in Flattern

```
Flatten::flushUrl('http://localhost/users/taylorotwell');
```

**Comment by freekmurze** [comment]
Flushing a part of this cache seperatly would be a nice enhancement. I'll solve this in an elegant way in a future release.

**Comment by kristjanjansen** [comment]
What is the status on the cache flush functionality?

**Comment by freekmurze** [comment]
Haven't come around to it yet. If you need this quick, feel free to submit a PR.

**Comment by freekmurze** [comment]
I'm probably only going to add this one when I need it myself. Currently that's not the case. If you need this submit a PR.

**Comment by Spir** [comment]
A quick way to flush a cache for a given URL:

```
$uri = 'http://localhost/users/taylorotwell';
$cacheProfile = new \Spatie\ResponseCache\CacheProfiles\CacheAllSuccessfulGetRequests(app());
$requestHasher = new \Spatie\ResponseCache\RequestHasher($cacheProfile);
$request = \Illuminate\Http\Request::create($uri);
$cacheKey = $requestHasher->getHashFor($request);
if (\Cache::has($cacheKey)) {
    \Cache::forget($cacheKey);
}
```

Very quick indeed, but if you need it that should make it.

**Comment by desh901** [comment]
Any progress on this aspect? By the way, great package and you guys are making an awesome work to make Laravel an even more complete framework!

**Comment by freekmurze** [comment]
Thanks for the kind words on our work.

Still don't have a need for this myself. I'd accept a fully tested non-breaking PR that adds this in a clean way.
