### ISSUE TITLE
if content changed, it don't update

### ISSUE THREAD

**Issue by MostafaRabia** [spatie/laravel-responsecache#308]
I need to update content for user if the content is same not updated, how is it?

**Comment by JosuelRocha** [comment]
You need to clear the cache of the route or routes affected by the new content.

ResponseCache::forget(['/some-uri', '/other-uri']);
https://github.com/spatie/laravel-responsecache#forget-one-or-several-specific-uris

Remembering that the cache must be for pages where the content is the same for all users / visitors.
