### ISSUE TITLE
PHP requirements out of line with target Laravel version

### ISSUE THREAD

**Issue by dariusj18** [spatie/laravel-responsecache#319]
This seems to have been addressed here and there in different issues, but there was never really a solid resolution or reason given.

Is there some policy that Spatie has that you can mention, so that people who want to know more in the future can find the answer here?

It seems rather strange to create requirements for a package that do not line up with the requirements for the framework it is meant for., and if there is some reason for it, it would be good to know.  I liked this package and wanted to use it in a project, however the inconsistent behavior means I will have to rewrite parts of it and drop this package.

**Comment by freekmurze** [comment]
It's not that hard. We don't use anything below 7.4 for our own projects, so we're not going to invest our time in package maintenance for that PHP version.

If you disagree, feel free to fork the package, and invest your time. I'd be happy to merge a PR that adds a link to your package in our readme.
