### ISSUE TITLE
[question] opposite option for doNotCacheResponse

### ISSUE THREAD

**Issue by rogervila** [spatie/laravel-responsecache#32]
Hello, 

I've seen that there is a `doNotCacheResponse` that prevents a route or an action to be cached.

I would like to know how to apply the opposite logic, disabling all routes except the ones that apply a middleware, for example:

```php
$this->middleware('cacheResponse', ['only' => ['fooAction', 'barAction']]);
```
Thank you.

**Comment by adrinavarro** [comment]
+1 on this, this way sounds saner to me. I just want to cache some public endpoints that are mostly static, for ~30min at a time.

**Comment by freekmurze** [comment]
All these scenarios are possible by [creating your own cache profile](https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile). This will allow you to specify in detail what should be cached and for how long.
