### ISSUE TITLE
Is there a way to disable it for local development

### ISSUE THREAD

**Issue by xoco70** [spatie/laravel-responsecache#320]
Hi, 

While I pretty much see the interest of the plugin for production, it may become difficult to have to make exceptions for local development each time I will create a new route.

Is there a way to disable the cache for local dev?

**Comment by freekmurze** [comment]
Use a cache profile that returns false for every request, or use an array cache.

**Comment by techbio** [comment]
Looks like setting a
`RESPONSE_CACHE_ENABLED=false`
environment variable in your development .env would be the simplest solution.
