### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by lucasctd** [spatie/laravel-responsecache#322]
I have done everything from the installation section.

What I have seen while debugging is that the class CacheResponse on line 29:
`if ($this->responseCache->hasBeenCached($request, $tags)) {`
It always returns false, so it never send the cached response.
Also on he ResponseCache file on line 51:
`$response = $this->addCachedHeader($response);`
I see the header is really set but when I look on postman, the header is not there.

May you help me?

Thanks in advance.

**Comment by freekmurze** [comment]
Unfortunately I don't have the time to look at specific projects. Ask for help on a forum like the Laracasts forum.

**Comment by lucasctd** [comment]
why don't just let anyone else try to help then?

**Comment by freekmurze** [comment]
We use this issue tracker to track problem with the package itself. Our tests indicate that the package is working as intended.

**Comment by lucasctd** [comment]
the pieces of code I quoted above are not from my project, they are from yours. I didn't get why it always return that the request is not cached, but okay, never mind.

**Comment by freekmurze** [comment]
Please PR a failing test to prove that it doesn't work. If possible also PR a fix. If both the test and fix are correct I'll merge it in.
