### ISSUE TITLE
Laravel 8.14.0

### ISSUE THREAD

**Issue by reina3596** [spatie/laravel-responsecache#323]
I have this error in a fresh installation of Laravel (8.14.0)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-responsecache ^6.3 -> satisfiable by spatie/laravel-responsecache[6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.6.1, 6.6.2, 6.6.3, 6.6.4, 6.6.5].
    - Installation request for laravel/framework (locked at v8.14.0, required as ^8.12) -> satisfiable by laravel/framework[v8.14.0].
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.13.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.14.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.14.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.14.0].
    - Conclusion: install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.12 -> satisfiable by laravel/framework[8.x-dev, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.14.0].

**Comment by freekmurze** [comment]
I can't help you with this kind of problem, make sure your app meets all requirements listed in composer.json.
