### ISSUE TITLE
Tenancy Cache Invalidation problem

### ISSUE THREAD

**Issue by dalholm** [spatie/laravel-responsecache#325]
I use this for a multi tenancy project and its awesome. :) Thanks! 

I do have some trouble with the invalidation of the Cache. I have my own custom CacheProfile and the CacheNameSuffix set to a unique id. But when i clear a specific route with `\ResponseCache::forget([route('tenant.list', ['slug' => $event->list->slug])]);` it seems to invalidate all the tenants, even though i run this command only on a particular tenant. 

Any ideas? :)

**Comment by freekmurze** [comment]
No idea. 

To seems that the failure is unrelated to this package. 

Feel free to submit a failing test for us to fix.
