### ISSUE TITLE
Disable cache from view

### ISSUE THREAD

**Issue by alvinbakker** [spatie/laravel-responsecache#33]
When a form is made on the fly we need to use the csrf token. As we want to cache the whole site except the pages with a form, it should be possible to exclude pages that have a csrf token in it. Of course if the page has it's own method this is possible with `$this->middleware('doNotCacheResponse');` from the controller. But what if the page does not have it's own method. How can we disable the csrf token to be cached also?

**Comment by freekmurze** [comment]
A cache profile has [a `shouldCacheResponse`  method](https://github.com/spatie/laravel-responsecache/blob/5a75c03/src/CacheProfiles/CacheProfile.php#L26) with which you can determine if the response should be cached.

You could try to find the csrf field in the body of the response.

**Comment by mgiorgi-github** [comment]
Hi, can you post an example for create and use custom profile end exclude specific URLs?
Thanks
