### ISSUE TITLE
Cache is becoming invalidated between calls has() and get()

### ISSUE THREAD

**Issue by f1amy** [spatie/laravel-responsecache#330]
Trying to reopen [#137](https://github.com/spatie/laravel-responsecache/issues/137).

For some reason after the cache repository confirms the response [`hasBeenCached()`](https://github.com/spatie/laravel-responsecache/blob/2a9cf083839e5ec5a7cd968e7779c85863901b6e/src/Middlewares/CacheResponse.php#L29),
trying to [`getCachedResponseFor()`](https://github.com/spatie/laravel-responsecache/blob/2a9cf083839e5ec5a7cd968e7779c85863901b6e/src/Middlewares/CacheResponse.php#L32) fails as [`unserialize()`](https://github.com/spatie/laravel-responsecache/blob/2a9cf083839e5ec5a7cd968e7779c85863901b6e/src/ResponseCacheRepository.php#L40) is getting `null` instead of a `string` from the cache.
This happens very rarely.

Exception:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Spatie\ResponseCache\Serializers\DefaultSerializer::unserialize() must be of the type string, null given, called in /srv/data/code/vendor/spatie/laravel-responsecache/src/ResponseCacheRepository.php on line 41
#58 /vendor/spatie/laravel-responsecache/src/Serializers/DefaultSerializer.php(20): Spatie\ResponseCache\Serializers\DefaultSerializer::unserialize
#57 /vendor/spatie/laravel-responsecache/src/ResponseCacheRepository.php(41): Spatie\ResponseCache\ResponseCacheRepository::get
#56 /vendor/spatie/laravel-responsecache/src/ResponseCache.php(74): Spatie\ResponseCache\ResponseCache::getCachedResponseFor
#55 /vendor/spatie/laravel-responsecache/src/Middlewares/CacheResponse.php(33): Spatie\ResponseCache\Middlewares\CacheResponse::handle
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#53 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
```

**Comment by freekmurze** [comment]
I'd welcome a PR to add a failing test to reproduce this error.

**Comment by f1amy** [comment]
I can do that, but as I said this issue happens rarely, so the test would be:
```
public function it_throws_an_exception_when_response_is_null()
{
    $this->expectException(TypeError::class);

    app(Serializer::class)->unserialize(null);
}
```
And I think that's not a good test, since the fix should be somewhere in [Middlewares/CacheResponse.php](https://github.com/spatie/laravel-responsecache/blob/2a9cf083839e5ec5a7cd968e7779c85863901b6e/src/Middlewares/CacheResponse.php#L32).
