### ISSUE TITLE
Replacer is not working when response is not cached

### ISSUE THREAD

**Issue by Zzombiee2361** [spatie/laravel-responsecache#343]
Now I know this has been reported before at #262, but I feel like I need to bring this up again.

I think this library should run `prepareResponseToCache` if the cache doesn't exists and store the response in cache, but then it should run `replaceInCachedResponse` and send the response. This way the placeholder will never be sent.

Also the replacer documentation is outdated, it should've been `prepareResponseToCache` instead of `transformInitialResponse`.  
Or is that method actually valid?

**Comment by KeitelDOG** [comment]
Hello I'm using the package and it's working. But I can't even see the Replacer codes in my version: I'm using `"spatie/laravel-responsecache": "^5.0",` , and it seems to be removed. Am I doing something wrong? Or is there any alternative?
