### ISSUE TITLE
problem clearing cache with different host name

### ISSUE THREAD

**Issue by ronald** [spatie/laravel-responsecache#354]
Thank you for providing this and other great packages :+1: 

We do cache all successfull get requests using the following profile:
```php
class Profile extends CacheAllSuccessfulGetRequests
{
    public function useCacheNameSuffix(Request $request): string
    {
        $agent = new Agent();
        $suffix = $agent->isDesktop() ? 'desktop-':  'mobile-';
        return $suffix;
   }
}
```
`
GET http://localhost/changed-page`
```php
ResponseCache::selectCachedItems()->usingSuffix('desktop-')->forUrls('/changed-page')->forget();
```
=> works

The project ist serving multiple host names so we really use:
`GET http://local.example.com/changed-page`
And the call
```php
ResponseCache::selectCachedItems()->usingSuffix('desktop-')->forUrls('/changed-page')->forget();
```
has no effect on http://local.example.com/changed-page (Looks like it assumes localhost internally).

Does the software support multiple hostnames?

**Comment by freekmurze** [comment]
@ivanomatteo could you take a look at this one?

**Comment by ivanomatteo** [comment]
@freekmurze sure! I think it's possible to add a new method 
`->forHosts([$hostname1, $hostname2])`

**Comment by freekmurze** [comment]
Feel free to PR that 👍

**Comment by ivanomatteo** [comment]
@ronald 
Anyway at the moment it's yet possible to manage:

it's enough to use:

`ResponseCache::selectCachedItems()->withHeaders(['Host'=>'site.com'])->forUrls('/changed-page')->forget();`

**Comment by ronald** [comment]
Thanks a lot.
