### ISSUE TITLE
Can't install older versions

### ISSUE THREAD

**Issue by rogervila** [spatie/laravel-responsecache#40]
Hi, 

I have a 5.3 project that can't be updated. I'd like to install an older version of this package. 

When I run this:
`composer require spatie/laravel-responsecache@1.1.7`

I get this message:
 `Could not find package spatie/laravel-responsecache@1.1.7 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

How can I install an older version without changing the `minimum-stability` value on my `composer.json`?

Thank you.

**Comment by blumtech** [comment]
I also had this issue. I've solved it running

composer require spatie/laravel-responsecache:v1

**Comment by rogervila** [comment]
I solved it by changing this values on my `composer.json`:

```json
"minimum-stability": "dev",
"prefer-stable": true
```
