### ISSUE TITLE
How can I confirm it is working?

### ISSUE THREAD

**Issue by zocheyado** [spatie/laravel-responsecache#47]
I followed the instructions on the setup page and I can't tell if it is working. The only part of the setup that did NOT work was the test `composer test` which says test is not defined. My network response time seems to be about the same ~2seconds. Any idea how I can confirm it is functioning? All of my responses are GET returning Response::json

**Comment by freekmurze** [comment]
By default it'll set an extra header if the `APP_DEBUG` variable is true: https://github.com/spatie/laravel-responsecache/blob/master/resources/config/laravel-responsecache.php#L25-L30

If it's not working for you please try installing it into a vanilla laravel app to check if it's working there. You can also take a look at the tests of this package on how this package can be used.

**Comment by zocheyado** [comment]
Does not seem to work on my application with debug set to true in app and .env files. I guess I can try a vanilla install. I suspect I am missing something.

**Comment by christophrumpel** [comment]
@freekmurze Any reason you only show the header when debug is true? For security reasons maybe?
