### ISSUE TITLE
Exception when using BinaryFileResponse

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-responsecache#5]
Issue reported by @sdebacker:

Hello Freek, I have this exception thrown, but I don’t know yet when and why. Do you see what is the problem ?

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()' in /home/forge/microstart.be/vendor/spatie/laravel-responsecache/src/ResponseCache.php:121
```

**Comment by freekmurze** [comment]
@sdebacker This is fixed in the newly tagged version 1.1.3

**Comment by sdebacker** [comment]
The problem occurs when using this package https://github.com/BKWLD/croppa for generating thumbs from a request.

**Comment by sdebacker** [comment]
ok nice

**Comment by freekmurze** [comment]
If you still encounter the problem with v1.1.3 of the package, reopen this issue.

**Comment by sdebacker** [comment]
It works like a charm.
