### ISSUE TITLE
Can't publish the config file, using PHP 5.6

### ISSUE THREAD

**Issue by goodjack** [spatie/laravel-responsecache#53]
When I executed the following command:
```zsh
php artisan vendor:publish --provider="Spatie\ResponseCache\ResponseCacheServiceProvider"
```

I got the error:
```zsh
PHP Parse error:  syntax error, unexpected ':', expecting '{' in /Users/jack/GitProject/hot-quiz/vendor/spatie/laravel-responsecache/src/ResponseCacheServiceProvider.php on line 28
```

I guess it's because of PHP 5.6, what should I do? Thanks!

--
Laravel version: 5.4.16
PHP version: 5.6.30

**Comment by freekmurze** [comment]
`v1` of this package is compatible with PHP 5.6.

But do yourself a favour and upgrade to PHP 7 asap. With a little bit of luck you might not need this package anymore 😎
