### ISSUE TITLE
Transform to Laravel 5.0.*

### ISSUE THREAD

**Issue by vanderb** [spatie/laravel-responsecache#6]
This is no Issue, but I think an enhancement.

First I would thank you for this great package. Our current project runs very slow, because of a large amount of database-queries. Average page-load was about 5s. After we had implemented this package, it's incredibely fast. Now the page loads in about 1-2s or faster (depending on amount of queries).

Like said in the readme, this package is for Laravel 5.1.
If your project runs with Laravel 5.0.*, this package can't be installd via composer (because of it's depencencies).

So. To make this package work with Laravel 5.0.*, follow my instructions:

1. Grab a copy if this package and unzip its contents to /vendor/spatie
2. Add the package classes to composers autoload-declaration in composer.json.

        "autoload": {
            "classmap": {
              "app",
               "vendor/spatie"
            }
        }

3. Update autoload-file: composer dump-autoload
4. Copy package-config-file to laravels config-directory

        "/vendor/spatie/laravel-responsecache/resources/config/laravel-responsecache.php" => "/config"

5. Add ServiceProvider and Package-Class to config/app.php. Please look at the different declarations of 5.0.* and 5.1.

        "providers" => [
                ...
                'Spatie\ResponseCache\ResponseCacheServiceProvider',

        "aliases" => [
                ...
                'ResponseCache' => 'Spatie\ResponseCache\ResponseCacheFacade',

6. Don't know if it's a general bug in this package, but in this case the name-property in the Command-Class is missing. So add this property to following file "vendor/spatie/laravel-responsecache/src/Commands/ClearCommand.php"

        protected $name = 'laravel-responsecache';

Simply quick & dirty, but works for me. Hope it's usefull for anyone.

**Comment by freekmurze** [comment]
Hi, regarding the missing name-property: in Laravel 5.1 this has been replaced with [signature](http://laravel.com/docs/5.1/artisan).
If there are any more requests for L5.0 compatibility I'll modify the package. But to all L5.0-users, the upgrade path to 5.1 is very easy :smile:
