### ISSUE TITLE
Error when running php artisan vendor:publish --provider="Spatie\ResponseCache\ResponseCacheServiceProvider"

### ISSUE THREAD

**Issue by alvinbakker** [spatie/laravel-responsecache#60]
I get this error on the latest version:

local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting '{'' in C:\WAMP\www\site\vendor\spatie\laravel-responsecache\src\ResponseCacheServiceProvider.php:28

**Comment by freekmurze** [comment]
This package is PHP 7.0. You're probably using an older version.

**Comment by alvinbakker** [comment]
Hi Freek,

So if I want to run ResponseCache dev-master version on Laravel 5.4.x I
will have to use PHP7?
Or is there another version that will run on PHP5.6.x and Laravel 5.4.x?

Kind regards / Met vriendelijke groet,
Alvin Bakker

SPIN Internet Media
Chonchorogaiweg 9, Willemstad, Curacao. T +5999 738 5611 http://www.spin.cw



Please consider the environment before printing this email

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination, publication
or copying of this e-mail is strictly prohibited. The sender does not
accept any responsibility for any loss, disruption or damage to your data
or computer system that may occur while using data contained in, or
transmitted with, this e-mail. If you have received this e-mail in error,
please immediately notify us by return e-mail.Thank you.

**Comment by freekmurze** [comment]
There currently isn't a version that supports both PHP5.6 and L5.4

I'd accept a PR that adds compatiblity for L5.4 to the `v1` branch of this package. Of course all the test should still be able to run.
