### ISSUE TITLE
Make the Handler extendable

### ISSUE THREAD

**Issue by bedeMarkRadford** [spatie/laravel-responsecache#62]
I want to be able to extend the handle method to add specific cases when I want to return the cached version, and when not to.

Use case:
For rapid delivery of home/content page, I want output caching on all routes.
As these pages contain a login form, I need that form ONLY for requests where the user is not logged in.
Once a user is logged in, I don't want to serve that user a cached page, as the form would be replaced by account details(or whatever).

**Comment by freekmurze** [comment]
You can already enable this kind of behaviour by creating your own [cache profile](https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile)

In `shouldCacheRequest` you could return `false` if you're on the home page and not logged in, in `cacheNameSuffix` you could return the id of the authenticated user.
