### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()

### ISSUE THREAD

**Issue by khaqanali** [spatie/laravel-responsecache#63]
Getting this error while downloading PDF file from storage dir. I am using laravel 5.4

**Comment by freekmurze** [comment]
The package should probably not cache that kind of responses. I'd accept a PR with tests that fixes this.

**Comment by akinolu52** [comment]
@freekmurze any help on this?

**Comment by akinolu52** [comment]
$response = $next($request);

$response->headers->set('Access-Control-Allow-Origin' , '*');
$response->headers->set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE');
$response->headers->set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With, Application');

return $response;


https://stackoverflow.com/questions/29289177/binaryfileresponse-in-laravel-undefined

That the solution

**Comment by freekmurze** [comment]
Feel free to PR a fix with tests.

**Comment by sebastiandedeyne** [comment]
You can modify your cache profile for this if needed. We'll add a list of sensible defaults in the next major version.

**Comment by msdavid1296** [comment]
I have added FrameHeadersMiddleware to handle the clickjacking. After this while downloading the pdf I am getting the following error.


(1/1) FatalThrowableErrorCall to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()
--
Any help?

**Comment by sebastiandedeyne** [comment]
Please share a full stack trace of your error in a new issue if you want us to look into this.

**Comment by MaykelLlanes** [comment]
The suggested solution by @akinolu52 worked form me. The difference in my code on ModifyHeadersMiddelware was the way to set the headers, i had $response->header(....) but when change it by $response->headers->set() worked well. Thanks to the community.

**Comment by ycamposde** [comment]
**Colution worked for me**

$response = $next($request);

$response->headers->set('Access-Control-Allow-Origin' , '*');
$response->headers->set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE');
$response->headers->set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With, Application');
