### ISSUE TITLE
Missing support for file/image response caching

### ISSUE THREAD

**Issue by TeRMiNaTe** [spatie/laravel-responsecache#66]
This package does not seem to handle caching file/image responses returned from controllers.  
  
Example Controller:
```
public function showImage(Request $request) {
	return response()->file(public_path('some_file.png'));
}
```

Error:
```
UnexpectedValueException in Response.php line 399: The Response content must be a string or object implementing __toString(), "boolean" given.
```

Unfortunately, this is a deal breaker for me. Hopefully it gets added/fixed.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes this.
