### ISSUE TITLE
shouldCache always returns false

### ISSUE THREAD

**Issue by alvinbakker** [spatie/laravel-responsecache#68]
I have upgraded my web app to Laravel 5.4 and also upgraded the ResponseCache package.  Whatever I do `if ($this->responseCache->shouldCache($request, $response))` from \Middlewares\CacheResponse.php keeps returning false. The only thing I have set in the controller is:

        if(config('html-caching') == false) {
            $this->middleware('doNotCacheResponse');
        }

And my guess is, this is correct and should not intervene with shouldCache when this config setting is set to true 

Or am I missing something here?

**Comment by freekmurze** [comment]
This is the implementation of `shouldCache`: https://github.com/spatie/laravel-responsecache/blob/777e0da116bfe65588015b32f3ea050fcffc698a/src/ResponseCache.php#L32-L43

Add some `dd` statements in there to figure out why it's always returning `false` in your app.

**Comment by alvinbakker** [comment]
Yes I did, and the / page is cached correctly, but all sub  pages give at `$request->attributes`
`responsecache.doNotCache = true` as return, while it's not set

**Comment by alvinbakker** [comment]
Never mind. I already found the flaw in my site
