### ISSUE TITLE
ResponseCache::flush() vs ResponseCache::flush('/regex/');

### ISSUE THREAD

**Issue by jaimeescano** [spatie/laravel-responsecache#72]
Hi,

While checking the library documentation, I'm just wondering if it could be possible to flush just part of the cache.

Example:
_1. A user "A" request product list -> then the response will be cached.
2. Same user "A" request the product list -> the cache will get a hit.
3. A different user "B" adds a new product.
4. The user "A" request the product list, then the return information will be wrong as the cache has different products that the real backend._

Is there any way that we could execute something like

      ResponseCache::flush( route('product.index') );

This will then remove all the cache queries that match any request to that specific named-route. This get more handy for JSON API's, as you can just wipe the cache for specific endpoint without affecting other endpoints.

I'll be more than happy to help if this can be considered.

Regards

**Comment by freekmurze** [comment]
Currently that is not possible. I tried to add this feature when creating the package, but I could not find a simple solution at the time.

I'd accept a readable, non breaking, fully tested PR that adds this to the package.

**Comment by ctf0** [comment]
this is possible by adding events for the backend CRUD ops, and add a listener maybe in `EventServiceProvider` that flush the cache accordingly.

for regex, check https://stackoverflow.com/questions/35074418/laravel-erase-all-cache-redis-keys-that-contain-a-specific-string
