### ISSUE TITLE
Don't serve cache to certain users (e.g., logged in, commenters)

### ISSUE THREAD

**Issue by bridgeport** [spatie/laravel-responsecache#75]
Instead of using `cacheNameSuffix()` to create a different cache for specific users, how about a way to prevent an already cached page from being served to certain users under certain conditions?

For instance, I have a page that accepts comments that are held in moderation until approved. The user will still see their pending comment as the site checks for a cookie variable specific to that user and runs a separate database query to render results specific to that user.

Everybody else, who does not have that recent commenter cookie, should get the cached page.

This is similar to how WordPress cache plugins work. All having the ability to prevent cached pages from being served to certain users:

* logged in
* recently made a comment

Thanks.

**Comment by sebastiandedeyne** [comment]
You could implement a custom cache profile to do this: https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile
