### ISSUE TITLE
Create hierarchical cache structure based on URL and folder path

### ISSUE THREAD

**Issue by bridgeport** [spatie/laravel-responsecache#76]
I understand you're piggybacking on Laravel's internal caching logic, but would you consider rolling your own caching system that's based on folder paths:

So instead of something like this:
```
/storage/framework/cache/data/0d/4e/0d4e10c8b2815260cebe7b3a1970254cc9eeb872
```

You'd have this:
```
/storage/framework/spatie-cache/https/example.dev/blog/article/index.html
/storage/framework/spatie-cache/https/example.dev/blog/categories/category1/index.html
/storage/framework/spatie-cache/https/example.dev/blog/categories/category2/index.html
```

Another issue asked if there's a way to clear caches based on a regex pattern: https://github.com/spatie/laravel-responsecache/issues/72

Which you said wasn't possible or was too complicated to deal with. If the cache was in a folder structure, it would allow users to implement cache clearing implementations without having to depend on this script based on other events.

It also makes the cache less ambiguous. Right now, everything is mixed together and it's not possible to tell what's what and where.

For instance, if a site had a blog that added a new post, a script could be written to clear all related pages, such as:
```
storage/framework/spatie-cache/https/example.dev/blog/*
```

Thanks.

**Comment by sebastiandedeyne** [comment]
We're not really interested in adding this to the package at the moment. This assumes you're using a file-based cache driver. This package woks with any cache driver usable in Laravel.

I think you could get pretty far in writing something like this using the hooks in the `CacheProfile` interface: https://github.com/spatie/laravel-responsecache#creating-a-custom-cache-profile
