### ISSUE TITLE
Flush cache base on request

### ISSUE THREAD

**Issue by khanhvu14** [spatie/laravel-responsecache#77]
I want clear cache base on request get param clear

My function
`
public function shouldCacheRequest(Request $request): bool
    {
        if ($request->ajax()) {
            return false;
        }

        if ($this->isRunningInConsole()) {
            return false;
        }

        if($request->clear){
            ResponseCache::flush();
            return false;
        }

        return $request->isMethod('get');
    }

`

but 

Class 'App\Helpers\CacheProfiles\ResponseCache' not found
--
 
How to fixed it?

**Comment by freekmurze** [comment]
You need to import the facade.

Add `use ResponseCache;` at the top of your file.

**Comment by khanhvu14** [comment]
Thank you
