### ISSUE TITLE
csrf token

### ISSUE THREAD

**Issue by monovm** [spatie/laravel-responsecache#84]
if a page have form with csrf token whats happend if we cache entire page ? 

regards

**Comment by monovm** [comment]
can we replace new csrf token on cached version

**Comment by freekmurze** [comment]
Take care not to cache pages where a form with server side processing is being displayed.

**Comment by monovm** [comment]
its not possible to replace token with new token on cached version ?

**Comment by monovm** [comment]
i think solution is this 
give variable to token value in form when we want create cache 
then when we want to send cached version to view we can give value to variable. 
i think in this way packge will support pages with csrf token too.
