### ISSUE TITLE
Reintroduce responsecache:clear

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-responsecache#85]
Right now we have a `flush` command, but `clear` is better. 

Let's make this happen with a non breaking change.

**Comment by maqui7295** [comment]
Hi, loved your creation responsecache. How do we use the cache tags specified in the config? there is no info on its usage. Thanks

**Comment by freekmurze** [comment]
Your question isn't really related to this issue. Feel free to create a new issue when you have questions.

This comment in the config file explains how the package will use tags: https://github.com/spatie/laravel-responsecache/blob/master/config/responsecache.php#L39-L43

**Comment by khanhvu14** [comment]
![screen shot 2017-09-05 at 10 32 03 pm](https://user-images.githubusercontent.com/4197632/30069173-227338cc-928a-11e7-945c-428318198918.png)
![screen shot 2017-09-05 at 10 32 15 pm](https://user-images.githubusercontent.com/4197632/30069174-22760c14-928a-11e7-8322-ff0382c9d412.png)
I want clear cache not in console, but i have this problem in 4.0.1  (Old version I can do that)

**Comment by BryanYeh** [comment]
@khanhvu14 I know ```Artisan::call('responsecache:flush');```` should work

**Comment by khanhvu14** [comment]
@BryanYeh  No, just work "ResponseCache::flush();"

**Comment by poor-bob** [comment]
So if this were implemented one could theoretically tag all responses with the currently logged in user ID and then clear by that tag upon a subsequent delete/update by said user ID?

I'm willing to contribute in any way I can if this seems the soundest way to achieve what I said above.

**Comment by khanhvu14** [comment]
I think we should cache a version cache (include guest and auth user) then using AJAX to reload some fragment of html contain user info.

**Comment by sebastiandedeyne** [comment]
In case anyone would like to PR this

- Add a `clear` method. Move all logic here, and `flush` should be an alias for `clear`. Mark `flush` as `@deprecated`
- Update the readme, rename `flush` to `clear` everywhere

**Comment by filipac** [comment]
@sebastiandedeyne what about the events? Shall I make new events and use those too? Like ClearedResponseCache

**Comment by sebastiandedeyne** [comment]
Sounds good, make sure you keep the old ones though!
