### ISSUE TITLE
Caching response different for all users?

### ISSUE THREAD

**Issue by BryanYeh** [spatie/laravel-responsecache#88]
I was trying out this package.
I am using 2 browsers to do some testing.

1. On Chrome, I go to <project>/post/a-big-post
2. In a new tab (Chrome), I edit the post (not using cache here)
3. I go back the the tab from 1,  and refresh the page... page returned is the cached version 👍 
4. Opening Firefox, I go to <project>/post/a-big-post, I do not get the cached version 😕 , I get the edited version

Is this suppose to happen?

**Comment by freekmurze** [comment]
This package does not take in account which browsers you're using. Try adding some serverside logging to verify if the server is really rerendering the package or using the cache.

**Comment by BryanYeh** [comment]
I did it a quick and dirty way of logging, edited the **ResponseCacheHit** and **ResponseCacheMiss**,
The server does reach/use the package. 

### Scenario 1
1. Open  /blog/post on a browser (ie. Chrome) **MISS**
	- Creates CACHE1
2. Edit the post using admin (same browser as 1.)
3. Refresh page from 1.  **HIT**
	- Uses CACHE1
4. Open /blog/post in a new browser or private window (ie. Firefox) **MISS**
	- Creates CACHE2
5. Refresh page from 1. browser, **HIT**
	- Uses CACHE1
6. Refresh page from 4. browser, **HIT**
	- Uses CACHE2
7. Edit the post using admin
8. Refresh page from 1. **HIT**
	- Uses CACHE1
9. Open /blog/post in a new browser or private window (ie. Chrome Private Window) **HIT**
	- Uses CACHE2

For some reason editing on the same browser/window, the cache is somehow messing up. like in the case of Scenario 1. I know clearing the cache after editing is the best thing to do, but in this scenario it should have stayed in CACHE1

### Scenario 2
1. Open admin to edit post, don't edit (ie. Chrome)
2. Open  /blog/post on a browser (ie. Firefox) **MISS**
	- Creates CACHE1
3. Edit post from 1. browser
4. Refresh 2. browser **HIT**
	- Uses CACHE1
5. Open /blog/post in a new browser or private window (ie. Chrome Private Window) **HIT**
	- Uses CACHE1

Scenario 2 works perfectly and stays with CACHE1.

**Comment by freekmurze** [comment]
This is the code that creates a unique hash for a request:

https://github.com/spatie/laravel-responsecache/blob/ba18210c3c42d0eb5ddf805bf55e20eb435e6206/src/RequestHasher.php#L21

Could you investigate here if it returns a different value when you visit it with different browsers?

**Comment by BryanYeh** [comment]
Okay, I have tested it out in 3 scenerios, with all the cache cleared, view cleared, session cleared:
1. Chrome (normal) for viewing post, Firefox (normal) for viewing post
   - hash is the same
2. 1 Chrome tab (normal) for admin logged in, 1 Chrome tab (normal) for viewing post , Firefox (normal)
   - hash is different
3. Chrome (normal), Chrome (private), Firefox (normal)
   - hash is same

I'm thinking it might be the routing problem. 
```
Route::get('blog/post/{slug}', ...

Route::group(['middleware' => 'doNotCacheResponse', 'prefix' => 'admin'], function () {
   Route::get('edit/post/{id}', ...
```

**Comment by khanhvu14** [comment]
@freekmurze 
I have a problem. 
I want to clear cache directly via custom GET param
Ex: bds123.vn?clear=1
This means that the RequestHasher will not include this GET param when generate hash key? 
Do you have add it to current config?

**Comment by sebastiandedeyne** [comment]
@BryanYeh Do you still have this issue? Anything we can still help investigating with, or can we close?
