### ISSUE TITLE
How to cache serialized responses

### ISSUE THREAD

**Issue by edbentinck** [spatie/laravel-responsecache#89]
Is there support for caching serialized responses? I am using Fractal to [transform my API responses](https://fractal.thephpleague.com/serializers/). For example:

```
{
    "data": [
        {
            'foo' => 'bar'
        }
    ],
   "meta": [
        ...
    ]
}
```

Currently the response is cached without being wrapped, meaning that subsequent requests are returned in their unserialized state.

**Comment by freekmurze** [comment]
Apart from adding a header, this package should not touch the content of the response itself. Could you PR a failing test for me to look at?

**Comment by edbentinck** [comment]
It's not a case of this package modifying the content of the response, but more a case of it storing the content of the `Response`, rather than the final content actually being returned.

From my brief amount of debugging it seems Fractal serializes the content after `Response` has  done its thing. i.e.:

```
Controller -> Response (cached at this point) -> Fractal -> data returned
```

If this is the case, I'm wondering what the alternative could be in order to cache the content in its serialized form. Any thoughts would be welcome. Otherwise I'll try and push that PR later today.

**Comment by freekmurze** [comment]
i'd accept a PR (preferably with tests) that resolves your problem.

**Comment by vjolenz** [comment]
@edbentinck; hey, do you still have this problem? I might have a solution but it needs to be tested

**Comment by edbentinck** [comment]
@vjolenz Due to time constraints I ended up adding [laravel-fractal](https://github.com/spatie/laravel-fractal) and using that instead of pure Fractal. It seemed to play a lot nicer with this package and I no longer ran into this issue. What were you thinking as a solution?

**Comment by sebastiandedeyne** [comment]
Gonna close this for now. If this is still an issue for someone, feel free to reopen, preferably with a failing test case.
